local HttpService, Players, RbxAnalyticsService, LogService, GuiService = game:GetService("HttpService"), game:GetService("Players"), game:GetService("RbxAnalyticsService"), game:GetService("LogService"), game:GetService("GuiService")
local cloneref = cloneref or function(o) return o end
local CoreGui, VirtualInputManager, UserInputService, RunService, TweenService = cloneref(game:GetService("CoreGui")), cloneref(game:GetService("VirtualInputManager")), cloneref(game:GetService("UserInputService")), cloneref(game:GetService("RunService")), cloneref(game:GetService("TweenService"))
local gethui = gethui or function() return CoreGui end
local request = (syn and syn.request) or (http and http.request) or http_request or (fluxus and fluxus.request) or request
local TOGGLE_KEY, MIN_CPM, MAX_CPM_LEGIT, MAX_CPM_BLATANT = Enum.KeyCode.RightControl, 50, 1500, 3000
local THEME = {Background = Color3.fromRGB(20, 20, 24), ItemBG = Color3.fromRGB(32, 32, 38), Accent = Color3.fromRGB(114, 100, 255), Text = Color3.fromRGB(240, 240, 240), SubText = Color3.fromRGB(150, 150, 160), Success = Color3.fromRGB(100, 255, 140), Warning = Color3.fromRGB(255, 200, 80), Slider = Color3.fromRGB(60, 60, 70)}
local ConfigFile, Config = "WordHelper_Config.json", {CPM = 550, Blatant = false, Humanize = true, FingerModel = true, SortMode = "Random", SuffixMode = "", LengthMode = 0, AutoPlay = false, AutoJoin = false, AutoJoinSettings = {_1v1 = true, _4p = true, _8p = true}, PanicMode = true, ShowKeyboard = false, ErrorRate = 5, ThinkDelay = 0.8, RiskyMistakes = false, CustomWords = {}, MinTypeSpeed = 50, MaxTypeSpeed = 3000, KeyboardLayout = "QWERTY"}
local currentCPM, isBlatant, useHumanization, useFingerModel, sortMode, suffixMode, lengthMode, autoPlay, autoJoin, panicMode, showKeyboard, errorRate, thinkDelayCurrent, riskyMistakes, keyboardLayout, isTyping, isAutoPlayScheduled, lastTypingStart, runConn, inputConn, logConn, unloaded, isMyTurnLogDetected, logRequiredLetters, turnExpiryTime, Blacklist, UsedWords, lastDetected, cachedDetected, cachedCensored, UpdateList, ButtonCache, ButtonData, JoinDebounce, listUpdatePending, forceUpdateList, lastInputTime, currentBestMatch, lastTimerVal, lastTimerTick, lastTypeVisible, lastRequiredLetter, StatsData, ShowToast, SmartType, ResetState, SearchBox, ScreenGui, Buckets, Words
local function SaveConfig() if writefile then writefile(ConfigFile, HttpService:JSONEncode(Config)) end end
local function LoadConfig() if isfile and isfile(ConfigFile) then local s, d = pcall(function() return HttpService:JSONDecode(readfile(ConfigFile)) end) if s and d then for k, v in pairs(d) do Config[k] = v end end end end
LoadConfig()
currentCPM, isBlatant, useHumanization, useFingerModel, sortMode, suffixMode, lengthMode, autoPlay, autoJoin, panicMode, showKeyboard, errorRate, thinkDelayCurrent, riskyMistakes, keyboardLayout = Config.CPM, Config.Blatant, Config.Humanize, Config.FingerModel, Config.SortMode, Config.SuffixMode or "", Config.LengthMode or 0, Config.AutoPlay, Config.AutoJoin, Config.PanicMode, Config.ShowKeyboard, Config.ErrorRate, Config.ThinkDelay, Config.RiskyMistakes, Config.KeyboardLayout or "QWERTY"
isTyping, isAutoPlayScheduled, lastTypingStart, unloaded, isMyTurnLogDetected, logRequiredLetters, turnExpiryTime, Blacklist, UsedWords, lastDetected, cachedDetected, cachedCensored, ButtonCache, ButtonData, JoinDebounce, listUpdatePending, forceUpdateList, lastInputTime, lastTimerVal, lastTimerTick, lastTypeVisible, lastRequiredLetter, StatsData, Words = false, false, 0, false, false, "", 0, {}, {}, "---", "", false, {}, {}, {}, false, false, 0, nil, 0, false, "", {}, {}
function ResetState(manual) UsedWords, lastDetected, forceUpdateList = {}, "---", true if SearchBox then SearchBox.Text = "" end if manual and ShowToast then ShowToast("Used words cleared!", "success") end if UpdateList then UpdateList("", "") end end
local function ColorToRGB(c) return string.format("%d,%d,%d", math.floor(c.R * 255), math.floor(c.G * 255), math.floor(c.B * 255)) end
local function Tween(obj, props, time) TweenService:Create(obj, TweenInfo.new(time or 0.2, Enum.EasingStyle.Quad, Enum.EasingDirection.Out), props):Play() end
local function GetCurrentGameWord(pf) local f = pf or (Players.LocalPlayer and Players.LocalPlayer:FindFirstChild("PlayerGui") and Players.LocalPlayer.PlayerGui:FindFirstChild("InGame") and Players.LocalPlayer.PlayerGui.InGame:FindFirstChild("Frame")) local ct = f and f:FindFirstChild("CurrentWord") if not ct then return "", false end local det, cen, letterData = "", false, {} for _, c in ipairs(ct:GetChildren()) do if c:IsA("GuiObject") and c.Visible then local txt = c:FindFirstChild("Letter") if txt and txt:IsA("TextLabel") and txt.TextTransparency < 1 then table.insert(letterData, {Obj = c, Txt = txt, X = c.AbsolutePosition.X, Id = tonumber(c.Name) or 0}) end end end table.sort(letterData, function(a,b) return math.abs(a.X-b.X) > 2 and a.X < b.X or a.Id < b.Id end) for _, d in ipairs(letterData) do local t = tostring(d.Txt.Text) if t:find("#") or t:find("%*") then cen = true end det = det .. t end return det:lower():gsub(" ", ""), cen end
local function GetTurnInfo(pf) if isMyTurnLogDetected then if tick() < turnExpiryTime then return true, logRequiredLetters else isMyTurnLogDetected = false end end local f = pf or (Players.LocalPlayer and Players.LocalPlayer:FindFirstChild("PlayerGui") and Players.LocalPlayer.PlayerGui:FindFirstChild("InGame") and Players.LocalPlayer.PlayerGui.InGame:FindFirstChild("Frame")) local tl = f and f:FindFirstChild("Type") if tl and tl:IsA("TextLabel") then local t, p = tl.Text, Players.LocalPlayer if t:sub(1, #p.Name) == p.Name or t:sub(1, #p.DisplayName) == p.DisplayName then return true, t:match("starting with:%s*([A-Za-z])") end end return false, nil end
logConn = LogService.MessageOut:Connect(function(m) local w, t = m:match("Word:%s*([A-Za-z]+)%s+Time to respond:%s*(%d+)") if w and t then isMyTurnLogDetected, logRequiredLetters, turnExpiryTime = true, w, tick() + tonumber(t) end end)
local LoadingGui = Instance.new("ScreenGui") LoadingGui.Name = "WordHelperLoading" local s, p = pcall(gethui) LoadingGui.Parent = (s and p) or game:GetService("CoreGui") local LoadingFrame = Instance.new("Frame", LoadingGui) LoadingFrame.Size, LoadingFrame.Position, LoadingFrame.BackgroundColor3, LoadingFrame.BorderSizePixel = UDim2.new(0, 300, 0, 100), UDim2.new(0.5, -150, 0.4, 0), THEME.Background, 0 Instance.new("UICorner", LoadingFrame).CornerRadius = UDim.new(0, 10) local LStroke = Instance.new("UIStroke", LoadingFrame) LStroke.Color, LStroke.Transparency, LStroke.Thickness = THEME.Accent, 0.5, 2 local LoadingTitle = Instance.new("TextLabel", LoadingFrame) LoadingTitle.Size, LoadingTitle.BackgroundTransparency, LoadingTitle.Text, LoadingTitle.TextColor3, LoadingTitle.Font, LoadingTitle.TextSize = UDim2.new(1, 0, 0, 40), 1, "WordHelper V4", THEME.Accent, Enum.Font.GothamBold, 18 local LoadingStatus = Instance.new("TextLabel", LoadingFrame) LoadingStatus.Size, LoadingStatus.Position, LoadingStatus.BackgroundTransparency, LoadingStatus.Text, LoadingStatus.TextColor3, LoadingStatus.Font, LoadingStatus.TextSize = UDim2.new(1, -20, 0, 30), UDim2.new(0, 10, 0, 50), 1, "Initializing...", THEME.Text, Enum.Font.Gotham, 14
local function UpdateStatus(t, c) LoadingStatus.Text = t if c then LoadingStatus.TextColor3 = c end RunService.RenderStepped:Wait() end
UpdateStatus("Fetching word list...", THEME.Warning) local res = request({Url = "https://raw.githubusercontent.com/skrylor/english-words/refs/heads/main/merged_english.txt", Method = "GET"}) if res and res.Body then writefile("ultimate_words_v4.txt", res.Body) end local SeenWords = {} if isfile("ultimate_words_v4.txt") then for w in readfile("ultimate_words_v4.txt"):gmatch("[^\r\n]+") do local cl = w:gsub("[%s%c]+", ""):lower() if #cl > 0 and not SeenWords[cl] then SeenWords[cl], Words[#Words+1] = true, cl end end end
table.sort(Words) Buckets = {} for _, w in ipairs(Words) do local c = w:sub(1,1) or "#" Buckets[c] = Buckets[c] or {} table.insert(Buckets[c], w) end if Config.CustomWords then for _, w in ipairs(Config.CustomWords) do local cl = w:gsub("[%s%c]+", ""):lower() if #cl > 0 and not SeenWords[cl] then SeenWords[cl] = true table.insert(Words, cl) local c = cl:sub(1,1) or "#" Buckets[c] = Buckets[c] or {} table.insert(Buckets[c], cl) end end end SeenWords, LoadingGui = nil, LoadingGui:Destroy()
ScreenGui = Instance.new("ScreenGui", p or game:GetService("CoreGui")) ScreenGui.Name, ScreenGui.ZIndexBehavior = tostring(math.random(1e6, 9e6)), Enum.ZIndexBehavior.Sibling
local ToastContainer = Instance.new("Frame", ScreenGui) ToastContainer.Name, ToastContainer.Size, ToastContainer.Position, ToastContainer.BackgroundTransparency, ToastContainer.ZIndex = "ToastContainer", UDim2.new(0, 300, 1, 0), UDim2.new(1, -320, 0, 20), 1, 100
ShowToast = function(m, t) local toast = Instance.new("Frame", ToastContainer) toast.Size, toast.BackgroundColor3, toast.BorderSizePixel, toast.BackgroundTransparency = UDim2.new(1, 0, 0, 40), THEME.ItemBG, 0, 1 local stroke = Instance.new("UIStroke", toast) stroke.Thickness, stroke.Transparency, stroke.Color = 1.5, 1, (t=="success" and THEME.Success or t=="warning" and THEME.Warning or Color3.fromRGB(255, 80, 80)) Instance.new("UICorner", toast).CornerRadius = UDim.new(0, 6) local lbl = Instance.new("TextLabel", toast) lbl.Size, lbl.Position, lbl.BackgroundTransparency, lbl.Text, lbl.TextColor3, lbl.Font, lbl.TextSize, lbl.TextWrapped, lbl.TextTransparency = UDim2.new(1, -20, 1, 0), UDim2.new(0, 10, 0, 0), 1, m, stroke.Color, Enum.Font.GothamMedium, 14, true, 1 Tween(toast, {BackgroundTransparency = 0.1}, 0.3) Tween(lbl, {TextTransparency = 0}, 0.3) Tween(stroke, {Transparency = 0.2}, 0.3) task.delay(3, function() if toast.Parent then Tween(toast, {BackgroundTransparency = 1}, 0.5) Tween(lbl, {TextTransparency = 1}, 0.5) Tween(stroke, {Transparency = 1}, 0.5) task.wait(0.5) toast:Destroy() end end) end
local MainFrame = Instance.new("Frame", ScreenGui) MainFrame.Name, MainFrame.Size, MainFrame.Position, MainFrame.BackgroundColor3, MainFrame.BorderSizePixel, MainFrame.Active, MainFrame.ClipsDescendants = "MainFrame", UDim2.new(0, 300, 0, 500), UDim2.new(0.8, -50, 0.4, 0), THEME.Background, 0, true, true
local function EnableDragging(f) local d, ds, sp f.InputBegan:Connect(function(i) if i.UserInputType == Enum.UserInputType.MouseButton1 or i.UserInputType == Enum.UserInputType.Touch then d, ds, sp = true, i.Position, f.Position i.Changed:Connect(function() if i.UserInputState == Enum.UserInputState.End then d = false end end) end end) UserInputService.InputChanged:Connect(function(i) if d and (i.UserInputType == Enum.UserInputType.MouseMovement or i.UserInputType == Enum.UserInputType.Touch) then local del = i.Position - ds f.Position = UDim2.new(sp.X.Scale, sp.X.Offset + del.X, sp.Y.Scale, sp.Y.Offset + del.Y) end end) end
EnableDragging(MainFrame) Instance.new("UICorner", MainFrame).CornerRadius = UDim.new(0, 10) local Stroke = Instance.new("UIStroke", MainFrame) Stroke.Color, Stroke.Transparency, Stroke.Thickness = THEME.Accent, 0.5, 2
local Header = Instance.new("Frame", MainFrame) Header.Size, Header.BackgroundColor3, Header.BorderSizePixel = UDim2.new(1, 0, 0, 45), THEME.ItemBG, 0 local TitleLbl = Instance.new("TextLabel", Header) TitleLbl.Text, TitleLbl.RichText, TitleLbl.Font, TitleLbl.TextSize, TitleLbl.TextColor3, TitleLbl.Size, TitleLbl.Position, TitleLbl.BackgroundTransparency, TitleLbl.TextXAlignment = "Word<font color=\"rgb(114,100,255)\">Helper</font> V4", true, Enum.Font.GothamBold, 18, THEME.Text, UDim2.new(1, -50, 1, 0), UDim2.new(0, 15, 0, 0), 1, Enum.TextXAlignment.Left
local MinBtn = Instance.new("TextButton", Header) MinBtn.Text, MinBtn.Font, MinBtn.TextSize, MinBtn.TextColor3, MinBtn.Size, MinBtn.Position, MinBtn.BackgroundTransparency = "-", Enum.Font.GothamBold, 24, THEME.SubText, UDim2.new(0, 45, 1, 0), UDim2.new(1, -90, 0, 0), 1
local CloseBtn = Instance.new("TextButton", Header) CloseBtn.Text, CloseBtn.Font, CloseBtn.TextSize, CloseBtn.TextColor3, CloseBtn.Size, CloseBtn.Position, CloseBtn.BackgroundTransparency = "X", Enum.Font.GothamBold, 18, Color3.fromRGB(255, 80, 80), UDim2.new(0, 45, 1, 0), UDim2.new(1, -45, 0, 0), 1 CloseBtn.MouseButton1Click:Connect(function() unloaded = true if runConn then runConn:Disconnect() end ScreenGui:Destroy() end)
local StatusFrame = Instance.new("Frame", MainFrame) StatusFrame.Size, StatusFrame.Position, StatusFrame.BackgroundTransparency = UDim2.new(1, -30, 0, 24), UDim2.new(0, 15, 0, 55), 1 local StatusDot = Instance.new("Frame", StatusFrame) StatusDot.Size, StatusDot.Position, StatusDot.BackgroundColor3 = UDim2.new(0, 8, 0, 8), UDim2.new(0, 0, 0.5, -4), THEME.SubText Instance.new("UICorner", StatusDot).CornerRadius = UDim.new(1, 0) local StatusText = Instance.new("TextLabel", StatusFrame) StatusText.Text, StatusText.RichText, StatusText.Font, StatusText.TextSize, StatusText.TextColor3, StatusText.Size, StatusText.Position, StatusText.BackgroundTransparency, StatusText.TextXAlignment = "Idle...", true, Enum.Font.Gotham, 12, THEME.SubText, UDim2.new(1, -15, 1, 0), UDim2.new(0, 15, 0, 0), 1, Enum.TextXAlignment.Left
SearchBox = Instance.new("TextBox", Instance.new("Frame", MainFrame)) SearchBox.Parent.Size, SearchBox.Parent.Position, SearchBox.Parent.BackgroundColor3 = UDim2.new(1, -10, 0, 26), UDim2.new(0, 5, 0, 82), THEME.ItemBG Instance.new("UICorner", SearchBox.Parent).CornerRadius = UDim.new(0, 6) SearchBox.Size, SearchBox.Position, SearchBox.BackgroundTransparency, SearchBox.Font, SearchBox.TextSize, SearchBox.TextColor3, SearchBox.PlaceholderText, SearchBox.Text = UDim2.new(1, -20, 1, 0), UDim2.new(0, 10, 0, 0), 1, Enum.Font.Gotham, 14, THEME.Text, "Search words...", "" SearchBox:GetPropertyChangedSignal("Text"):Connect(function() if UpdateList then UpdateList(lastDetected, lastRequiredLetter) end end)
local ScrollList = Instance.new("ScrollingFrame", MainFrame) ScrollList.Size, ScrollList.Position, ScrollList.BackgroundTransparency, ScrollList.ScrollBarThickness, ScrollList.ScrollBarImageColor3, ScrollList.CanvasSize = UDim2.new(1, -10, 1, -220), UDim2.new(0, 5, 0, 115), 1, 3, THEME.Accent, UDim2.new(0,0,0,0) local UIListLayout = Instance.new("UIListLayout", ScrollList) UIListLayout.SortOrder, UIListLayout.Padding = Enum.SortOrder.LayoutOrder, UDim.new(0, 4)
local SettingsFrame = Instance.new("Frame", MainFrame) SettingsFrame.BackgroundColor3, SettingsFrame.BorderSizePixel, SettingsFrame.ClipsDescendants = THEME.ItemBG, 0, true local SlidersFrame, TogglesFrame = Instance.new("Frame", SettingsFrame), Instance.new("Frame", SettingsFrame) SlidersFrame.Size, SlidersFrame.BackgroundTransparency = UDim2.new(1, 0, 0, 125), 1 TogglesFrame.Size, TogglesFrame.Position, TogglesFrame.BackgroundTransparency, TogglesFrame.Visible = UDim2.new(1, 0, 0, 310), UDim2.new(0, 0, 0, 125), 1, false
local settingsCollapsed, ExpandBtn = true, Instance.new("TextButton", SlidersFrame) local function UpdateLayout() if settingsCollapsed then Tween(SettingsFrame, {Size = UDim2.new(1, 0, 0, 125), Position = UDim2.new(0, 0, 1, -125)}) Tween(ScrollList, {Size = UDim2.new(1, -10, 1, -245)}) TogglesFrame.Visible = false else Tween(SettingsFrame, {Size = UDim2.new(1, 0, 0, 435), Position = UDim2.new(0, 0, 1, -435)}) Tween(ScrollList, {Size = UDim2.new(1, -10, 1, -555)}) TogglesFrame.Visible = true end end
UpdateLayout() ExpandBtn.Text, ExpandBtn.Font, ExpandBtn.TextColor3, ExpandBtn.BackgroundColor3, ExpandBtn.BackgroundTransparency, ExpandBtn.Size, ExpandBtn.Position = "v Settings v", Enum.Font.GothamBold, THEME.Accent, Color3.fromRGB(40, 40, 45), 0.5, UDim2.new(1, -10, 0, 30), UDim2.new(0, 5, 1, -35) Instance.new("UICorner", ExpandBtn).CornerRadius = UDim.new(0, 6) ExpandBtn.MouseButton1Click:Connect(function() settingsCollapsed = not settingsCollapsed ExpandBtn.Text = settingsCollapsed and "v Settings v" or "^ Settings ^" UpdateLayout() end)
local function SetupSlider(btn, bg, fill, cb) btn.MouseButton1Down:Connect(function() local m, r function Update() local mp = UserInputService:GetMouseLocation() local pct = math.clamp(mp.X - bg.AbsolutePosition.X, 0, bg.AbsoluteSize.X) / bg.AbsoluteSize.X cb(pct) Config.CPM, Config.ErrorRate, Config.ThinkDelay = currentCPM, errorRate, thinkDelayCurrent end Update() m, r = RunService.RenderStepped:Connect(Update), UserInputService.InputEnded:Connect(function(inp) if inp.UserInputType == Enum.UserInputType.MouseButton1 or inp.UserInputType == Enum.UserInputType.Touch then if m then m:Disconnect() end if r then r:Disconnect() end SaveConfig() end end) end) end
local function CreateToggle(t, p, cb) local b = Instance.new("TextButton", TogglesFrame) b.Text, b.Font, b.TextSize, b.TextColor3, b.BackgroundColor3, b.Size, b.Position = t, Enum.Font.GothamMedium, 11, THEME.Success, THEME.Background, UDim2.new(0, 85, 0, 24), p Instance.new("UICorner", b).CornerRadius = UDim.new(0, 4) b.MouseButton1Click:Connect(function() local s, nt, nc = cb() b.Text, b.TextColor3 = nt, nc SaveConfig() end) return b end
local function CreateCheckbox(t, p, k) local c = Instance.new("TextButton", TogglesFrame) c.Size, c.Position, c.BackgroundColor3, c.Text = UDim2.new(0, 90, 0, 24), p, THEME.ItemBG, "" Instance.new("UICorner", c).CornerRadius = UDim.new(0, 4) local b = Instance.new("Frame", c) b.Size, b.Position, b.BackgroundColor3 = UDim2.new(0, 14, 0, 14), UDim2.new(0, 5, 0.5, -7), THEME.Slider Instance.new("UICorner", b).CornerRadius = UDim.new(0, 3) local ch = Instance.new("Frame", b) ch.Size, ch.Position, ch.BackgroundColor3, ch.Visible = UDim2.new(0, 8, 0, 8), UDim2.new(0.5, -4, 0.5, -4), THEME.Success, Config.AutoJoinSettings[k] local l = Instance.new("TextLabel", c) l.Text, l.Font, l.TextSize, l.TextColor3, l.Size, l.Position, l.BackgroundTransparency, l.TextXAlignment = t, Enum.Font.GothamMedium, 11, (Config.AutoJoinSettings[k] and THEME.Text or THEME.SubText), UDim2.new(1, -25, 1, 0), UDim2.new(0, 25, 0, 0), 1, Enum.TextXAlignment.Left c.MouseButton1Click:Connect(function() Config.AutoJoinSettings[k] = not Config.AutoJoinSettings[k] ch.Visible, l.TextColor3 = Config.AutoJoinSettings[k], (Config.AutoJoinSettings[k] and THEME.Text or THEME.SubText) SaveConfig() end) return c end
CreateToggle("Humanize: "..(useHumanization and "ON" or "OFF"), UDim2.new(0, 15, 0, 5), function() useHumanization = not useHumanization return useHumanization, "Humanize: "..(useHumanization and "ON" or "OFF"), useHumanization and THEME.Success or Color3.fromRGB(255, 100, 100) end) CreateToggle("10-Finger: "..(useFingerModel and "ON" or "OFF"), UDim2.new(0, 105, 0, 5), function() useFingerModel = not useFingerModel return useFingerModel, "10-Finger: "..(useFingerModel and "ON" or "OFF"), useFingerModel and THEME.Success or Color3.fromRGB(255, 100, 100) end) CreateToggle("Auto Play: "..(autoPlay and "ON" or "OFF"), UDim2.new(0, 15, 0, 33), function() autoPlay = not autoPlay return autoPlay, "Auto Play: "..(autoPlay and "ON" or "OFF"), autoPlay and THEME.Success or Color3.fromRGB(255, 100, 100) end).Size = UDim2.new(0, 130, 0, 24) CreateCheckbox("1v1", UDim2.new(0, 15, 0, 88), "_1v1") CreateCheckbox("4 Player", UDim2.new(0, 110, 0, 88), "_4p") CreateCheckbox("8 Player", UDim2.new(0, 205, 0, 88), "_8p")
local ClearUsedBtn = Instance.new("TextButton", TogglesFrame) ClearUsedBtn.Text, ClearUsedBtn.Font, ClearUsedBtn.TextSize, ClearUsedBtn.TextColor3, ClearUsedBtn.BackgroundColor3, ClearUsedBtn.Size, ClearUsedBtn.Position = "Clear Used Words", Enum.Font.GothamMedium, 11, THEME.Warning, THEME.Background, UDim2.new(0, 265, 0, 24), UDim2.new(0, 15, 0, 235) Instance.new("UICorner", ClearUsedBtn).CornerRadius = UDim.new(0, 4) ClearUsedBtn.MouseButton1Click:Connect(function() ResetState(true) end)
local function GetKeyCode(c) local l = Config.KeyboardLayout or "QWERTY" if type(c)=="string" and #c==1 then c = c:lower() if l=="QWERTZ" and c=="z" then return Enum.KeyCode.Y elseif l=="QWERTZ" and c=="y" then return Enum.KeyCode.Z end return Enum.KeyCode[c:upper()] end end
local function SimulateKey(i) if typeof(i)=="string" and #i==1 then if not pcall(function() VirtualInputManager:SendTextInput(i) end) then local k = GetKeyCode(i) if k then VirtualInputManager:SendKeyEvent(true, k, false, game) task.wait(0.01) VirtualInputManager:SendKeyEvent(false, k, false, game) end end else local k = typeof(i)=="EnumItem" and i or Enum.KeyCode[i:upper()] if k then VirtualInputManager:SendKeyEvent(true, k, false, game) task.wait(0.01) VirtualInputManager:SendKeyEvent(false, k, false, game) end end end
local function Backspace(c) local f = UserInputService:GetFocusedTextBox() if f and f.TextEditable then f.Text = f.Text:sub(1, -c-1) return end for i=1,c do SimulateKey(Enum.KeyCode.Backspace) end end
SmartType = function(tW, cD, isC, bP) if unloaded or isTyping then return end isTyping, lastTypingStart = true, tick() local tb = (Players.LocalPlayer and Players.LocalPlayer:FindFirstChild("PlayerGui") and Players.LocalPlayer.PlayerGui:FindFirstChild("InGame") and Players.LocalPlayer.PlayerGui.InGame:FindFirstChild("Frame"):FindFirstChildWhichIsA("TextBox")) or UserInputService:GetFocusedTextBox() if tb then tb:CaptureFocus() end pcall(function() local mP = tW:sub(1,#cD)==cD and tW:sub(#cD+1) or tW for i=1,#mP do if not bP and not GetTurnInfo() then break end local ch = mP:sub(i,i) SimulateKey(ch) task.wait(60/currentCPM) end SimulateKey(Enum.KeyCode.Return) task.wait(0.2) if GetCurrentGameWord()~="" then UsedWords[tW] = true end end) isTyping = false end
UpdateList = function(dT, rL) local matches, sP = {}, SearchBox.Text:lower():gsub("[%s%c]+", "") if sP=="" then sP = dT end local fC = sP:sub(1,1) if fC=="" or fC=="#" then fC = rL and rL:sub(1,1):lower() or "#" end for _, w in ipairs(Buckets[fC] or Words) do if not UsedWords[w] and w:sub(1,#sP)==sP then table.insert(matches, w) if #matches>=40 then break end end end for i=1, math.max(40, #ButtonCache) do local w, btn = matches[i], ButtonCache[i] if w then if not btn then btn = Instance.new("TextButton", ScrollList) btn.Size, btn.BackgroundColor3, btn.Text = UDim2.new(1, -6, 0, 30), THEME.ItemBG, "" local lbl = Instance.new("TextLabel", btn) lbl.Name, lbl.Size, lbl.BackgroundTransparency, lbl.Font, lbl.TextColor3, lbl.RichText = "Label", UDim2.new(1,0,1,0), 1, Enum.Font.GothamMedium, THEME.Text, true btn.MouseButton1Click:Connect(function() SmartType(w, dT, true) end) table.insert(ButtonCache, btn) end btn.Visible, btn.Label.Text = true, "<font color=\"rgb("..ColorToRGB(THEME.Accent)..")\">"..w:sub(1,#sP).."</font>"..w:sub(#sP+1) else if btn then btn.Visible = false end end end ScrollList.CanvasSize = UDim2.new(0,0,0, UIListLayout.AbsoluteContentSize.Y) end
local sf = Instance.new("Frame", ScreenGui) sf.Size, sf.Position, sf.BackgroundColor3 = UDim2.new(0, 120, 0, 60), UDim2.new(0.5, -60, 0, 10), THEME.Background local st = Instance.new("TextLabel", sf) st.Size, st.TextColor3, st.Font, st.Text = UDim2.new(1,0,0,30), THEME.Text, Enum.Font.GothamBold, "--"
RunService.RenderStepped:Connect(function() if unloaded then return end local n, p = tick(), Players.LocalPlayer local g = p and p:FindFirstChild("PlayerGui") local f = g and g:FindFirstChild("InGame") and g.InGame:FindFirstChild("Frame") local vis = f and f.Parent and (f.Parent:IsA("ScreenGui") and f.Parent.Enabled or f.Parent.Visible) local secs = nil if vis then local cir = f:FindFirstChild("Circle") local tL = cir and cir:FindFirstChild("Timer") and cir.Timer:FindFirstChild("Seconds") if tL then secs = tonumber(tL.Text:match("([%d%.]+)")) st.Text = tL.Text if secs and secs ~= lastTimerVal then lastTimerVal, lastTimerTick = secs, n end end end if n - lastTimerTick > 2 and next(UsedWords) then ResetState() end local imT, rL = GetTurnInfo(f) local det = GetCurrentGameWord(f) if det ~= lastDetected or rL ~= lastRequiredLetter or forceUpdateList then lastDetected, lastRequiredLetter, forceUpdateList = det, rL, false UpdateList(det, rL) StatusText.Text = (det=="" and "Waiting..." or "Input: "..det) end if autoPlay and not isTyping and imT and det==lastDetected and #det>=0 then task.spawn(function() task.wait(0.5) if GetTurnInfo() then local match = matches and matches[1] if match then SmartType(match, det, false) end end end) end end)
inputConn = UserInputService.InputBegan:Connect(function(i) if not unloaded and i.KeyCode == TOGGLE_KEY then ScreenGui.Enabled = not ScreenGui.Enabled end end)
