local HttpService, CoreGui, Players = game:GetService("HttpService"), game:GetService("CoreGui"), game:GetService("Players")
local RbxAnalyticsService, RunService, TweenService = game:GetService("RbxAnalyticsService"), game:GetService("RunService"), game:GetService("TweenService")
local LogService, GuiService = game:GetService("LogService"), game:GetService("GuiService")
local cloneref = cloneref or function(o) return o end
local gethui = gethui or function() return CoreGui end
local CoreGui, Players, VirtualInputManager = cloneref(game:GetService("CoreGui")), cloneref(game:GetService("Players")), cloneref(game:GetService("VirtualInputManager"))
local UserInputService, RunService, TweenService = cloneref(game:GetService("UserInputService")), cloneref(game:GetService("RunService")), cloneref(game:GetService("TweenService"))
local request = (syn and syn.request) or (http and http.request) or http_request or (fluxus and fluxus.request) or request
local TOGGLE_KEY, MIN_CPM, MAX_CPM_LEGIT, MAX_CPM_BLATANT = Enum.KeyCode.RightControl, 50, 1500, 3000
math.randomseed(os.time())
local THEME = {Background=Color3.fromRGB(20,20,24), ItemBG=Color3.fromRGB(32,32,38), Accent=Color3.fromRGB(114,100,255), Text=Color3.fromRGB(240,240,240), SubText=Color3.fromRGB(150,150,160), Success=Color3.fromRGB(100,255,140), Warning=Color3.fromRGB(255,200,80), Slider=Color3.fromRGB(60,60,70)}
local function ColorToRGB(c) return string.format("%d,%d,%d", math.floor(c.R*255), math.floor(c.G*255), math.floor(c.B*255)) end
local ConfigFile = "WordHelper_Config.json"
local Config = {CPM=550, Blatant=false, Humanize=true, FingerModel=true, SortMode="Random", SuffixMode="", LengthMode=0, AutoPlay=false, AutoJoin=false, AutoJoinSettings={_1v1=true, _4p=true, _8p=true}, PanicMode=true, ShowKeyboard=false, ErrorRate=5, ThinkDelay=0.8, RiskyMistakes=false, CustomWords={}, MinTypeSpeed=50, MaxTypeSpeed=3000, KeyboardLayout="QWERTY"}
local function SaveConfig() if writefile then writefile(ConfigFile, HttpService:JSONEncode(Config)) end end
local function LoadConfig() if isfile and isfile(ConfigFile) then local s, d = pcall(function() return HttpService:JSONDecode(readfile(ConfigFile)) end) if s and d then for k,v in pairs(d) do Config[k]=v end end end end
LoadConfig()
local currentCPM, isBlatant, useHumanization = Config.CPM, Config.Blatant, Config.Humanize
local useFingerModel, sortMode, suffixMode, lengthMode = Config.FingerModel, Config.SortMode, Config.SuffixMode or "", Config.LengthMode or 0
local autoPlay, autoJoin, panicMode, showKeyboard = Config.AutoPlay, Config.AutoJoin, Config.PanicMode, Config.ShowKeyboard
local errorRate, thinkDelayCurrent, riskyMistakes, keyboardLayout = Config.ErrorRate, Config.ThinkDelay, Config.RiskyMistakes, Config.KeyboardLayout or "QWERTY"
local isTyping, isAutoPlayScheduled, lastTypingStart, unloaded = false, false, 0, false
local runConn, inputConn, logConn, isMyTurnLogDetected, logRequiredLetters, turnExpiryTime = nil, nil, nil, false, "", 0
local Blacklist, UsedWords, RandomOrderCache, RandomPriority = {}, {}, {}, {}
local lastDetected, lastLogicUpdate, lastAutoJoinCheck, lastWordCheck = "---", 0, 0, 0
local cachedDetected, cachedCensored, LOGIC_RATE, AUTO_JOIN_RATE = "", false, 0.1, 0.5
local UpdateList, ButtonCache, ButtonData, JoinDebounce = nil, {}, {}, {}
local thinkDelayMin, thinkDelayMax, listUpdatePending, forceUpdateList = 0.4, 1.2, false, false
local lastInputTime, LIST_DEBOUNCE, currentBestMatch = 0, 0.05, nil
if logConn then logConn:Disconnect() end
logConn = LogService.MessageOut:Connect(function(m, t) local w,time = m:match("Word:%s*([A-Za-z]+)%s+Time to respond:%s*(%d+)") if w and time then isMyTurnLogDetected, logRequiredLetters, turnExpiryTime = true, w, tick()+tonumber(time) end end)
local url, fileName = "https://raw.githubusercontent.com/skrylor/english-words/refs/heads/main/merged_english.txt", "ultimate_words_v4.txt"
local LoadingGui = Instance.new("ScreenGui"); LoadingGui.Name="WordHelperLoading"; local s,p = pcall(function() return gethui() end); if not s or not p then p=game:GetService("CoreGui") end; LoadingGui.Parent=p; LoadingGui.ZIndexBehavior=Enum.ZIndexBehavior.Sibling
local LoadingFrame = Instance.new("Frame", LoadingGui); LoadingFrame.Size=UDim2.new(0,300,0,100); LoadingFrame.Position=UDim2.new(0.5,-150,0.4,0); LoadingFrame.BackgroundColor3=THEME.Background; Instance.new("UICorner", LoadingFrame).CornerRadius=UDim.new(0,10)
local LStroke = Instance.new("UIStroke", LoadingFrame); LStroke.Color=THEME.Accent; LStroke.Transparency=0.5; LStroke.Thickness=2
local LoadingTitle = Instance.new("TextLabel", LoadingFrame); LoadingTitle.Size=UDim2.new(1,0,0,40); LoadingTitle.BackgroundTransparency=1; LoadingTitle.Text="WordHelper V4"; LoadingTitle.TextColor3=THEME.Accent; LoadingTitle.Font=Enum.Font.GothamBold; LoadingTitle.TextSize=18
local LoadingStatus = Instance.new("TextLabel", LoadingFrame); LoadingStatus.Size=UDim2.new(1,-20,0,30); LoadingStatus.Position=UDim2.new(0,10,0,50); LoadingStatus.BackgroundTransparency=1; LoadingStatus.Text="Initializing..."; LoadingStatus.TextColor3=THEME.Text; LoadingStatus.Font=Enum.Font.Gotham; LoadingStatus.TextSize=14
local function UpdateStatus(t, c) LoadingStatus.Text=t; if c then LoadingStatus.TextColor3=c end game:GetService("RunService").RenderStepped:Wait() end
local function FetchWords() UpdateStatus("Fetching latest word list...", THEME.Warning); local s,r = pcall(function() return request({Url=url, Method="GET"}) end) if s and r and r.Body then writefile(fileName, r.Body) UpdateStatus("Fetched successfully!", THEME.Success) else UpdateStatus("Fetch failed! Using cached.", Color3.fromRGB(255,80,80)) end task.wait(0.5) end
FetchWords(); local Words, SeenWords = {}, {}
local function LoadList(fname) UpdateStatus("Parsing word list...", THEME.Warning); if isfile(fname) then local c = readfile(fname) for w in c:gmatch("[^\r\n]+") do local cl = w:gsub("[%s%c]+",""):lower() if #cl>0 and not SeenWords[cl] then SeenWords[cl]=true table.insert(Words, cl) end end UpdateStatus("Loaded "..#Words.." words!", THEME.Success) else UpdateStatus("No word list found!", Color3.fromRGB(255,80,80)) end task.wait(1) end
LoadList(fileName); if LoadingGui then LoadingGui:Destroy() end
table.sort(Words); local Buckets = {}
for _,w in ipairs(Words) do local c=w:sub(1,1) or ""; if c=="" then c="#" end Buckets[c]=Buckets[c] or {}; table.insert(Buckets[c], w) end
if Config.CustomWords then for _,w in ipairs(Config.CustomWords) do local cl=w:gsub("[%s%c]+",""):lower(); if #cl>0 and not SeenWords[cl] then SeenWords[cl]=true; table.insert(Words, cl); local c=cl:sub(1,1) or ""; if c=="" then c="#" end Buckets[c]=Buckets[c] or {}; table.insert(Buckets[c], cl) end end end
SeenWords = nil
local function shuffleTable(t) for i=#t,2,-1 do local j=math.random(i); t[i],t[j]=t[j],t[i] end return t end
local HardLetterScores = {x=10, z=9, q=9, j=8, v=6, k=5, b=4, f=3, w=3, y=2, g=2, p=2}
local function GetKillerScore(word) return HardLetterScores[word:sub(-1)] or 0 end
local function Tween(obj, props, time) TweenService:Create(obj, TweenInfo.new(time or 0.2, Enum.EasingStyle.Quad, Enum.EasingDirection.Out), props):Play() end
local function GetCurrentGameWord(providedFrame)
    local frame = providedFrame; if not frame then local p=Players.LocalPlayer; local g=p and p:FindFirstChild("PlayerGui"); local ig=g and g:FindFirstChild("InGame"); frame=ig and ig:FindFirstChild("Frame") end
    local container = frame and frame:FindFirstChild("CurrentWord"); if not container then return "", false end
    local detected, censored, letterData = "", false, {}
    for _,c in ipairs(container:GetChildren()) do if c:IsA("GuiObject") and c.Visible then local t=c:FindFirstChild("Letter") if t and t:IsA("TextLabel") and t.TextTransparency<1 then table.insert(letterData, {Obj=c, Txt=t, X=c.AbsolutePosition.X, Id=tonumber(c.Name) or 0}) end end end
    table.sort(letterData, function(a,b) return (math.abs(a.X-b.X)>2) and (a.X<b.X) or (a.Id<b.Id) end)
    for _,d in ipairs(letterData) do local t=tostring(d.Txt.Text); if t:find("#") or t:find("%*") then censored=true end detected=detected..t end
    return detected:lower():gsub(" ",""), censored
end
local function GetTurnInfo(providedFrame)
    if isMyTurnLogDetected then if tick()<turnExpiryTime then return true, logRequiredLetters else isMyTurnLogDetected=false end end
    local frame = providedFrame; if not frame then local p=Players.LocalPlayer; local g=p and p:FindFirstChild("PlayerGui"); local ig=g and g:FindFirstChild("InGame"); frame=ig and ig:FindFirstChild("Frame") end
    local typeLbl = frame and frame:FindFirstChild("Type")
    if typeLbl and typeLbl:IsA("TextLabel") then local txt=typeLbl.Text; local p=Players.LocalPlayer
        if txt:sub(1,#p.Name)==p.Name or txt:sub(1,#p.DisplayName)==p.DisplayName then return true, txt:match("starting with:%s*([A-Za-z])") end
    end return false, nil
end
local function GetSecureParent() local s,r=pcall(gethui); if s and r then return r end; s,r=pcall(function() return CoreGui end); if s and r then return r end return Players.LocalPlayer.PlayerGui end
local ParentTarget, GuiName = GetSecureParent(), tostring(math.random(1000000, 9999999))
local env = (getgenv and getgenv()) or _G; if env.WordHelperInstance and env.WordHelperInstance.Parent then env.WordHelperInstance:Destroy() end
local ScreenGui = Instance.new("ScreenGui"); ScreenGui.Name=GuiName; ScreenGui.Parent=ParentTarget; ScreenGui.ZIndexBehavior=Enum.ZIndexBehavior.Sibling; env.WordHelperInstance=ScreenGui
local ToastContainer = Instance.new("Frame", ScreenGui); ToastContainer.Name="ToastContainer"; ToastContainer.Size=UDim2.new(0,300,1,0); ToastContainer.Position=UDim2.new(1,-320,0,20); ToastContainer.BackgroundTransparency=1; ToastContainer.ZIndex=100
local function ShowToast(msg, type)
    local t=Instance.new("Frame"); t.Size=UDim2.new(1,0,0,40); t.BackgroundColor3=THEME.ItemBG; t.BackgroundTransparency=1; t.Parent=ToastContainer; local s=Instance.new("UIStroke",t); s.Thickness=1.5; s.Transparency=1; local c=THEME.Text
    if type=="success" then c=THEME.Success elseif type=="warning" then c=THEME.Warning elseif type=="error" then c=Color3.fromRGB(255,80,80) end s.Color=c; Instance.new("UICorner",t).CornerRadius=UDim.new(0,6)
    local l=Instance.new("TextLabel",t); l.Size=UDim2.new(1,-20,1,0); l.Position=UDim2.new(0,10,0,0); l.BackgroundTransparency=1; l.Text=msg; l.TextColor3=c; l.Font=Enum.Font.GothamMedium; l.TextSize=14; l.TextTransparency=1
    Tween(t,{BackgroundTransparency=0.1},0.3); Tween(l,{TextTransparency=0},0.3); Tween(s,{Transparency=0.2},0.3)
    task.delay(3, function() if t and t.Parent then Tween(t,{BackgroundTransparency=1},0.5); Tween(l,{TextTransparency=1},0.5); Tween(s,{Transparency=1},0.5); task.wait(0.5); t:Destroy() end end)
end
local MainFrame = Instance.new("Frame"); MainFrame.Name="MainFrame"; MainFrame.Size=UDim2.new(0,300,0,500); MainFrame.Position=UDim2.new(0.8,-50,0.4,0); MainFrame.BackgroundColor3=THEME.Background; MainFrame.Active=true; MainFrame.ClipsDescendants=true; MainFrame.Parent=ScreenGui
local function EnableDragging(frame)
    local dragging, dragInput, dragStart, startPos; local function Update(input) local delta=input.Position-dragStart; frame.Position=UDim2.new(startPos.X.Scale, startPos.X.Offset+delta.X, startPos.Y.Scale, startPos.Y.Offset+delta.Y) end
    frame.InputBegan:Connect(function(inp) if inp.UserInputType==Enum.UserInputType.MouseButton1 or inp.UserInputType==Enum.UserInputType.Touch then dragging=true; dragStart=inp.Position; startPos=frame.Position; inp.Changed:Connect(function() if inp.UserInputState==Enum.UserInputState.End then dragging=false end end) end end)
    frame.InputChanged:Connect(function(inp) if inp.UserInputType==Enum.UserInputType.MouseMovement or inp.UserInputType==Enum.UserInputType.Touch then dragInput=inp end end)
    UserInputService.InputChanged:Connect(function(inp) if inp==dragInput and dragging then Update(inp) end end)
end
EnableDragging(MainFrame); Instance.new("UICorner", MainFrame).CornerRadius=UDim.new(0,10); local Stroke=Instance.new("UIStroke", MainFrame); Stroke.Color=THEME.Accent; Stroke.Transparency=0.5; Stroke.Thickness=2
local Header=Instance.new("Frame", MainFrame); Header.Size=UDim2.new(1,0,0,45); Header.BackgroundColor3=THEME.ItemBG; local Title=Instance.new("TextLabel", Header); Title.Text="Word<font color=\"rgb(114,100,255)\">Helper</font> V4"; Title.RichText=true; Title.Font=Enum.Font.GothamBold; Title.TextSize=18; Title.TextColor3=THEME.Text; Title.Size=UDim2.new(1,-50,1,0); Title.Position=UDim2.new(0,15,0,0); Title.BackgroundTransparency=1; Title.TextXAlignment=Enum.TextXAlignment.Left
local MinBtn=Instance.new("TextButton", Header); MinBtn.Text="-"; MinBtn.Font=Enum.Font.GothamBold; MinBtn.TextSize=24; MinBtn.TextColor3=THEME.SubText; MinBtn.Size=UDim2.new(0,45,1,0); MinBtn.Position=UDim2.new(1,-90,0,0); MinBtn.BackgroundTransparency=1
local CloseBtn=Instance.new("TextButton", Header); CloseBtn.Text="X"; CloseBtn.Font=Enum.Font.GothamBold; CloseBtn.TextSize=18; CloseBtn.TextColor3=Color3.fromRGB(255,80,80); CloseBtn.Size=UDim2.new(0,45,1,0); CloseBtn.Position=UDim2.new(1,-45,0,0); CloseBtn.BackgroundTransparency=1
CloseBtn.MouseButton1Click:Connect(function() unloaded=true; if runConn then runConn:Disconnect() end if inputConn then inputConn:Disconnect() end if logConn then logConn:Disconnect() end for _,b in ipairs(ButtonCache) do b:Destroy() end if ScreenGui then ScreenGui:Destroy() end end)
local StatusFrame=Instance.new("Frame", MainFrame); StatusFrame.Size=UDim2.new(1,-30,0,24); StatusFrame.Position=UDim2.new(0,15,0,55); StatusFrame.BackgroundTransparency=1
local StatusDot=Instance.new("Frame", StatusFrame); StatusDot.Size=UDim2.new(0,8,0,8); StatusDot.Position=UDim2.new(0,0,0.5,-4); StatusDot.BackgroundColor3=THEME.SubText; Instance.new("UICorner", StatusDot).CornerRadius=UDim.new(1,0)
local StatusText=Instance.new("TextLabel", StatusFrame); StatusText.Text="Idle..."; StatusText.RichText=true; StatusText.Font=Enum.Font.Gotham; StatusText.TextSize=12; StatusText.TextColor3=THEME.SubText; StatusText.Size=UDim2.new(1,-15,1,0); StatusText.Position=UDim2.new(0,15,0,0); StatusText.BackgroundTransparency=1; StatusText.TextXAlignment=Enum.TextXAlignment.Left
local SearchFrame=Instance.new("Frame", MainFrame); SearchFrame.Size=UDim2.new(1,-10,0,26); SearchFrame.Position=UDim2.new(0,5,0,82); SearchFrame.BackgroundColor3=THEME.ItemBG; Instance.new("UICorner", SearchFrame).CornerRadius=UDim.new(0,6)
local SearchBox=Instance.new("TextBox", SearchFrame); SearchBox.Size=UDim2.new(1,-20,1,0); SearchBox.Position=UDim2.new(0,10,0,0); SearchBox.BackgroundTransparency=1; SearchBox.Font=Enum.Font.Gotham; SearchBox.TextSize=14; SearchBox.TextColor3=THEME.Text; SearchBox.PlaceholderText="Search words..."; SearchBox.PlaceholderColor3=THEME.SubText; SearchBox.TextXAlignment=Enum.TextXAlignment.Left
SearchBox:GetPropertyChangedSignal("Text"):Connect(function() if UpdateList then UpdateList(lastDetected, lastRequiredLetter) end end)
local ScrollList=Instance.new("ScrollingFrame", MainFrame); ScrollList.Size=UDim2.new(1,-10,1,-220); ScrollList.Position=UDim2.new(0,5,0,115); ScrollList.BackgroundTransparency=1; ScrollList.ScrollBarThickness=3; ScrollList.ScrollBarImageColor3=THEME.Accent
local UIListLayout=Instance.new("UIListLayout", ScrollList); UIListLayout.SortOrder=Enum.SortOrder.LayoutOrder; UIListLayout.Padding=UDim.new(0,4)
local SettingsFrame=Instance.new("Frame", MainFrame); SettingsFrame.BackgroundColor3=THEME.ItemBG; SettingsFrame.ClipsDescendants=true; local SlidersFrame=Instance.new("Frame", SettingsFrame); SlidersFrame.Size=UDim2.new(1,0,0,125); SlidersFrame.BackgroundTransparency=1
local TogglesFrame=Instance.new("Frame", SettingsFrame); TogglesFrame.Size=UDim2.new(1,0,0,310); TogglesFrame.Position=UDim2.new(0,0,0,125); TogglesFrame.BackgroundTransparency=1; TogglesFrame.Visible=false; local sep=Instance.new("Frame", SettingsFrame); sep.Size=UDim2.new(1,0,0,1); sep.BackgroundColor3=Color3.fromRGB(45,45,50)
local settingsCollapsed = true; local function UpdateLayout() if settingsCollapsed then Tween(SettingsFrame,{Size=UDim2.new(1,0,0,125),Position=UDim2.new(0,0,1,-125)}); Tween(ScrollList,{Size=UDim2.new(1,-10,1,-245)}); TogglesFrame.Visible=false else Tween(SettingsFrame,{Size=UDim2.new(1,0,0,435),Position=UDim2.new(0,0,1,-435)}); Tween(ScrollList,{Size=UDim2.new(1,-10,1,-555)}); TogglesFrame.Visible=true end end
UpdateLayout(); local ExpandBtn=Instance.new("TextButton", SlidersFrame); ExpandBtn.Text="v Show Settings v"; ExpandBtn.Font=Enum.Font.GothamBold; ExpandBtn.TextSize=14; ExpandBtn.TextColor3=THEME.Accent; ExpandBtn.BackgroundColor3=Color3.fromRGB(40,40,45); ExpandBtn.BackgroundTransparency=0.5; ExpandBtn.Size=UDim2.new(1,-10,0,30); ExpandBtn.Position=UDim2.new(0,5,1,-35); Instance.new("UICorner", ExpandBtn).CornerRadius=UDim.new(0,6)
ExpandBtn.MouseButton1Click:Connect(function() settingsCollapsed=not settingsCollapsed; ExpandBtn.Text=settingsCollapsed and "v Show Settings v" or "^ Hide Settings ^"; UpdateLayout() end)
local function SetupSlider(btn, bg, fill, cb) btn.MouseButton1Down:Connect(function() local m,r; local function U() local mp=UserInputService:GetMouseLocation(); local rx=math.clamp(mp.X-bg.AbsolutePosition.X,0,bg.AbsoluteSize.X); cb(rx/bg.AbsoluteSize.X); Config.CPM, Config.ErrorRate, Config.ThinkDelay = currentCPM, errorRate, thinkDelayCurrent end U(); m=RunService.RenderStepped:Connect(U); r=UserInputService.InputEnded:Connect(function(i) if i.UserInputType==Enum.UserInputType.MouseButton1 or i.UserInputType==Enum.UserInputType.Touch then if m then m:Disconnect() end if r then r:Disconnect() end SaveConfig() end end) end) end
local KeyboardFrame = Instance.new("Frame", ScreenGui); KeyboardFrame.Name="KeyboardFrame"; KeyboardFrame.Size=UDim2.new(0,400,0,160); KeyboardFrame.Position=UDim2.new(0.1,0,0.5,-80); KeyboardFrame.BackgroundColor3=THEME.Background; KeyboardFrame.Visible=showKeyboard; EnableDragging(KeyboardFrame); Instance.new("UICorner", KeyboardFrame).CornerRadius=UDim.new(0,8); Instance.new("UIStroke", KeyboardFrame).Color=THEME.Accent
local Keys = {}; local function CreateKey(c,p,s) local k=Instance.new("Frame", KeyboardFrame); k.Size=s or UDim2.new(0,30,0,30); k.Position=p; k.BackgroundColor3=THEME.ItemBG; Instance.new("UICorner", k).CornerRadius=UDim.new(0,4); local l=Instance.new("TextLabel", k); l.Size=UDim2.new(1,0,1,0); l.BackgroundTransparency=1; l.Text=c:upper(); l.TextColor3=THEME.Text; l.Font=Enum.Font.GothamBold; l.TextSize=14; Keys[c:lower()]=k return k end
local function GenerateKeyboard()
    for _,c in ipairs(KeyboardFrame:GetChildren()) do if c:IsA("Frame") or c:IsA("TextLabel") then c:Destroy() end end Keys = {}
    local rows; if keyboardLayout=="QWERTZ" then rows={{"q","w","e","r","t","z","u","i","o","p"},{"a","s","d","f","g","h","j","k","l"},{"y","x","c","v","b","n","m"}} elseif keyboardLayout=="AZERTY" then rows={{"a","z","e","r","t","y","u","i","o","p"},{"q","s","d","f","g","h","j","k","l","m"},{"w","x","c","v","b","n"}} else rows={{"q","w","e","r","t","y","u","i","o","p"},{"a","s","d","f","g","h","j","k","l"},{"z","x","c","v","b","n","m"}} end
    for r,rc in ipairs(rows) do local sx=(400-(#rc*35))/2; for i,c in ipairs(rc) do CreateKey(c, UDim2.new(0,sx+(i-1)*35,0,15+(r-1)*35)) end end
    local sp=CreateKey(" ", UDim2.new(0.5,-100,0,120), UDim2.new(0,200,0,30)); sp:FindFirstChild("TextLabel").Text="SPACE"
end
GenerateKeyboard()
local function CreateDropdown(p,t,opts,d,cb)
    local c=Instance.new("Frame",p); c.Size=UDim2.new(0,130,0,24); c.BackgroundColor3=THEME.Background; c.ZIndex=10; Instance.new("UICorner",c).CornerRadius=UDim.new(0,4)
    local m=Instance.new("TextButton",c); m.Size=UDim2.new(1,0,1,0); m.BackgroundTransparency=1; m.Text=t..": "..d; m.Font=Enum.Font.GothamMedium; m.TextSize=11; m.TextColor3=THEME.Accent; m.ZIndex=11
    local l=Instance.new("Frame",c); l.Size=UDim2.new(1,0,0,#opts*24); l.Position=UDim2.new(0,0,1,2); l.BackgroundColor3=THEME.ItemBG; l.Visible=false; l.ZIndex=20; Instance.new("UICorner",l).CornerRadius=UDim.new(0,4)
    m.MouseButton1Click:Connect(function() l.Visible=not l.Visible end)
    for i,o in ipairs(opts) do local b=Instance.new("TextButton",l); b.Size=UDim2.new(1,0,0,24); b.Position=UDim2.new(0,0,0,(i-1)*24); b.BackgroundTransparency=1; b.Text=o; b.Font=Enum.Font.Gotham; b.TextSize=11; b.TextColor3=THEME.Text; b.ZIndex=21; b.MouseButton1Click:Connect(function() m.Text=t..": "..o; l.Visible=false; cb(o) end) end return c
end
local LayoutDropdown = CreateDropdown(TogglesFrame, "Layout", {"QWERTY", "QWERTZ", "AZERTY"}, keyboardLayout, function(v) keyboardLayout=v; Config.KeyboardLayout=v; GenerateKeyboard(); SaveConfig() end); LayoutDropdown.Position=UDim2.new(0,150,0,145)
UserInputService.InputBegan:Connect(function(i) if showKeyboard and i.UserInputType==Enum.UserInputType.Keyboard then local c=i.KeyCode.Name:lower(); if Keys[c] then Tween(Keys[c],{BackgroundColor3=THEME.Accent},0.1) elseif i.KeyCode==Enum.KeyCode.Space then Tween(Keys[" "],{BackgroundColor3=THEME.Accent},0.1) end end end)
UserInputService.InputEnded:Connect(function(i) if showKeyboard and i.UserInputType==Enum.UserInputType.Keyboard then local c=i.KeyCode.Name:lower(); if Keys[c] then Tween(Keys[c],{BackgroundColor3=THEME.ItemBG},0.2) elseif i.KeyCode==Enum.KeyCode.Space then Tween(Keys[" "],{BackgroundColor3=THEME.ItemBG},0.2) end end end)
local SliderLabel=Instance.new("TextLabel", SlidersFrame); SliderLabel.Text="Speed: "..currentCPM.." CPM"; SliderLabel.Font=Enum.Font.GothamMedium; SliderLabel.TextSize=12; SliderLabel.TextColor3=THEME.SubText; SliderLabel.Size=UDim2.new(1,-30,0,20); SliderLabel.Position=UDim2.new(0,15,0,8); SliderLabel.BackgroundTransparency=1; SliderLabel.TextXAlignment=Enum.TextXAlignment.Left
local SliderBg=Instance.new("Frame", SlidersFrame); SliderBg.Size=UDim2.new(1,-30,0,6); SliderBg.Position=UDim2.new(0,15,0,30); SliderBg.BackgroundColor3=THEME.Slider; Instance.new("UICorner", SliderBg).CornerRadius=UDim.new(1,0)
local SliderFill=Instance.new("Frame", SliderBg); SliderFill.Size=UDim2.new(0.5,0,1,0); SliderFill.BackgroundColor3=THEME.Accent; Instance.new("UICorner", SliderFill).CornerRadius=UDim.new(1,0); local SliderBtn=Instance.new("TextButton", SliderBg); SliderBtn.Size=UDim2.new(1,0,1,0); SliderBtn.BackgroundTransparency=1; SliderBtn.Text=""
local ErrorLabel=Instance.new("TextLabel", SlidersFrame); ErrorLabel.Text="Error Rate: "..errorRate.."%"; ErrorLabel.Font=Enum.Font.GothamMedium; ErrorLabel.TextSize=11; ErrorLabel.TextColor3=THEME.SubText; ErrorLabel.Size=UDim2.new(1,-30,0,18); ErrorLabel.Position=UDim2.new(0,15,0,36); ErrorLabel.BackgroundTransparency=1; ErrorLabel.TextXAlignment=Enum.TextXAlignment.Left
local ErrorBg=Instance.new("Frame", SlidersFrame); ErrorBg.Size=UDim2.new(1,-30,0,6); ErrorBg.Position=UDim2.new(0,15,0,56); ErrorBg.BackgroundColor3=THEME.Slider; Instance.new("UICorner", ErrorBg).CornerRadius=UDim.new(1,0)
local ErrorFill=Instance.new("Frame", ErrorBg); ErrorFill.Size=UDim2.new(errorRate/30,0,1,0); ErrorFill.BackgroundColor3=Color3.fromRGB(200,100,100); Instance.new("UICorner", ErrorFill).CornerRadius=UDim.new(1,0); local ErrorBtn=Instance.new("TextButton", ErrorBg); ErrorBtn.Size=UDim2.new(1,0,1,0); ErrorBtn.BackgroundTransparency=1; ErrorBtn.Text=""
SetupSlider(ErrorBtn, ErrorBg, ErrorFill, function(p) errorRate=math.floor(p*30); Config.ErrorRate=errorRate; ErrorFill.Size=UDim2.new(p,0,1,0); ErrorLabel.Text="Error Rate: "..errorRate.."% (per-letter)" end)
local ThinkLabel=Instance.new("TextLabel", SlidersFrame); ThinkLabel.Text=string.format("Think: %.2fs", thinkDelayCurrent); ThinkLabel.Font=Enum.Font.GothamMedium; ThinkLabel.TextSize=11; ThinkLabel.TextColor3=THEME.SubText; ThinkLabel.Size=UDim2.new(1,-30,0,18); ThinkLabel.Position=UDim2.new(0,15,0,62); ThinkLabel.BackgroundTransparency=1; ThinkLabel.TextXAlignment=Enum.TextXAlignment.Left
local ThinkBg=Instance.new("Frame", SlidersFrame); ThinkBg.Size=UDim2.new(1,-30,0,6); ThinkBg.Position=UDim2.new(0,15,0,82); ThinkBg.BackgroundColor3=THEME.Slider; Instance.new("UICorner", ThinkBg).CornerRadius=UDim.new(1,0)
local ThinkFill=Instance.new("Frame", ThinkBg); local tp=(thinkDelayCurrent-thinkDelayMin)/(thinkDelayMax-thinkDelayMin); ThinkFill.Size=UDim2.new(tp,0,1,0); ThinkFill.BackgroundColor3=THEME.Accent; Instance.new("UICorner", ThinkFill).CornerRadius=UDim.new(1,0); local ThinkBtn=Instance.new("TextButton", ThinkBg); ThinkBtn.Size=UDim2.new(1,0,1,0); ThinkBtn.BackgroundTransparency=1; ThinkBtn.Text=""
SetupSlider(ThinkBtn, ThinkBg, ThinkFill, function(p) thinkDelayCurrent=thinkDelayMin+p*(thinkDelayMax-thinkDelayMin); Config.ThinkDelay=thinkDelayCurrent; ThinkFill.Size=UDim2.new(p,0,1,0); ThinkLabel.Text=string.format("Think: %.2fs", thinkDelayCurrent) end)
local function CreateToggle(t,p,cb) local b=Instance.new("TextButton", TogglesFrame); b.Text=t; b.Font=Enum.Font.GothamMedium; b.TextSize=11; b.TextColor3=THEME.Success; b.BackgroundColor3=THEME.Background; b.Size=UDim2.new(0,85,0,24); b.Position=p; Instance.new("UICorner", b).CornerRadius=UDim.new(0,4); b.MouseButton1Click:Connect(function() local s,nt,nc=cb(); b.Text=nt; b.TextColor3=nc; SaveConfig() end) return b end
local HumanizeBtn=CreateToggle("Humanize: "..(useHumanization and "ON" or "OFF"), UDim2.new(0,15,0,5), function() useHumanization=not useHumanization; Config.Humanize=useHumanization; return useHumanization, "Humanize: "..(useHumanization and "ON" or "OFF"), useHumanization and THEME.Success or Color3.fromRGB(255,100,100) end)
local FingerBtn=CreateToggle("10-Finger: "..(useFingerModel and "ON" or "OFF"), UDim2.new(0,105,0,5), function() useFingerModel=not useFingerModel; Config.FingerModel=useFingerModel; return useFingerModel, "10-Finger: "..(useFingerModel and "ON" or "OFF"), useFingerModel and THEME.Success or Color3.fromRGB(255,100,100) end)
local KeyboardBtn=CreateToggle("Keyboard: "..(showKeyboard and "ON" or "OFF"), UDim2.new(0,195,0,5), function() showKeyboard=not showKeyboard; Config.ShowKeyboard=showKeyboard; KeyboardFrame.Visible=showKeyboard; return showKeyboard, "Keyboard: "..(showKeyboard and "ON" or "OFF"), showKeyboard and THEME.Success or Color3.fromRGB(255,100,100) end)
local SortBtn=CreateToggle("Sort: "..sortMode, UDim2.new(0,15,0,33), function() if sortMode=="Random" then sortMode="Shortest" elseif sortMode=="Shortest" then sortMode="Longest" elseif sortMode=="Longest" then sortMode="Killer" else sortMode="Random" end Config.SortMode=sortMode; lastDetected="---"; return true, "Sort: "..sortMode, THEME.Accent end); SortBtn.TextColor3=THEME.Accent; SortBtn.Size=UDim2.new(0,130,0,24)
local AutoBtn=CreateToggle("Auto Play: "..(autoPlay and "ON" or "OFF"), UDim2.new(0,150,0,33), function() autoPlay=not autoPlay; Config.AutoPlay=autoPlay; return autoPlay, "Auto Play: "..(autoPlay and "ON" or "OFF"), autoPlay and THEME.Success or Color3.fromRGB(255,100,100) end); AutoBtn.TextColor3=autoPlay and THEME.Success or Color3.fromRGB(255,100,100); AutoBtn.Size=UDim2.new(0,130,0,24)
local AutoJoinBtn=CreateToggle("Auto Join: "..(autoJoin and "ON" or "OFF"), UDim2.new(0,15,0,61), function() autoJoin=not autoJoin; Config.AutoJoin=autoJoin; return autoJoin, "Auto Join: "..(autoJoin and "ON" or "OFF"), autoJoin and THEME.Success or Color3.fromRGB(255,100,100) end); AutoJoinBtn.TextColor3=autoJoin and THEME.Success or Color3.fromRGB(255,100,100); AutoJoinBtn.Size=UDim2.new(0,265,0,24)
local function CreateCheckbox(t,p,k) local c=Instance.new("TextButton", TogglesFrame); c.Size=UDim2.new(0,90,0,24); c.Position=p; c.BackgroundColor3=THEME.ItemBG; c.Text=""; Instance.new("UICorner", c).CornerRadius=UDim.new(0,4); local b=Instance.new("Frame", c); b.Size=UDim2.new(0,14,0,14); b.Position=UDim2.new(0,5,0.5,-7); b.BackgroundColor3=THEME.Slider; Instance.new("UICorner", b).CornerRadius=UDim.new(0,3); local ch=Instance.new("Frame", b); ch.Size=UDim2.new(0,8,0,8); ch.Position=UDim2.new(0.5,-4,0.5,-4); ch.BackgroundColor3=THEME.Success; ch.Visible=Config.AutoJoinSettings[k]; Instance.new("UICorner", ch).CornerRadius=UDim.new(0,2); local l=Instance.new("TextLabel", c); l.Text=t; l.Font=Enum.Font.GothamMedium; l.TextSize=11; l.TextColor3=THEME.SubText; l.Size=UDim2.new(1,-25,1,0); l.Position=UDim2.new(0,25,0,0); l.BackgroundTransparency=1; l.TextXAlignment=Enum.TextXAlignment.Left; c.MouseButton1Click:Connect(function() Config.AutoJoinSettings[k]=not Config.AutoJoinSettings[k]; ch.Visible=Config.AutoJoinSettings[k]; if Config.AutoJoinSettings[k] then l.TextColor3=THEME.Text; Tween(b,{BackgroundColor3=THEME.Accent},0.2) else l.TextColor3=THEME.SubText; Tween(b,{BackgroundColor3=THEME.Slider},0.2) end SaveConfig() end); if Config.AutoJoinSettings[k] then l.TextColor3=THEME.Text; b.BackgroundColor3=THEME.Accent end return c end
CreateCheckbox("1v1", UDim2.new(0,15,0,88), "_1v1"); CreateCheckbox("4 Player", UDim2.new(0,110,0,88), "_4p"); CreateCheckbox("8 Player", UDim2.new(0,205,0,88), "_8p")
local BlatantBtn=CreateToggle("Blatant Mode: "..(isBlatant and "ON" or "OFF"), UDim2.new(0,15,0,115), function() isBlatant=not isBlatant; Config.Blatant=isBlatant; return isBlatant, "Blatant Mode: "..(isBlatant and "ON" or "OFF"), isBlatant and Color3.fromRGB(255,80,80) or THEME.SubText end); BlatantBtn.TextColor3=isBlatant and Color3.fromRGB(255,80,80) or THEME.SubText; BlatantBtn.Size=UDim2.new(0,130,0,24)
local RiskyBtn=CreateToggle("Risky Mistakes: "..(riskyMistakes and "ON" or "OFF"), UDim2.new(0,150,0,115), function() riskyMistakes=not riskyMistakes; Config.RiskyMistakes=riskyMistakes; return riskyMistakes, "Risky Mistakes: "..(riskyMistakes and "ON" or "OFF"), riskyMistakes and Color3.fromRGB(255,80,80) or THEME.SubText end); RiskyBtn.TextColor3=riskyMistakes and Color3.fromRGB(255,80,80) or THEME.SubText; RiskyBtn.Size=UDim2.new(0,130,0,24)
local ManageWordsBtn=Instance.new("TextButton", TogglesFrame); ManageWordsBtn.Text="Manage Custom Words"; ManageWordsBtn.Font=Enum.Font.GothamMedium; ManageWordsBtn.TextSize=11; ManageWordsBtn.TextColor3=THEME.Accent; ManageWordsBtn.BackgroundColor3=THEME.Background; ManageWordsBtn.Size=UDim2.new(0,130,0,24); ManageWordsBtn.Position=UDim2.new(0,15,0,145); Instance.new("UICorner", ManageWordsBtn).CornerRadius=UDim.new(0,4)
local WordBrowserBtn=Instance.new("TextButton", TogglesFrame); WordBrowserBtn.Text="Word Browser"; WordBrowserBtn.Font=Enum.Font.GothamMedium; WordBrowserBtn.TextSize=11; WordBrowserBtn.TextColor3=Color3.fromRGB(200,150,255); WordBrowserBtn.BackgroundColor3=THEME.Background; WordBrowserBtn.Size=UDim2.new(0,265,0,24); WordBrowserBtn.Position=UDim2.new(0,15,0,175); Instance.new("UICorner", WordBrowserBtn).CornerRadius=UDim.new(0,4)
local ServerBrowserBtn=Instance.new("TextButton", TogglesFrame); ServerBrowserBtn.Text="Server Browser"; ServerBrowserBtn.Font=Enum.Font.GothamMedium; ServerBrowserBtn.TextSize=11; ServerBrowserBtn.TextColor3=Color3.fromRGB(100,200,255); ServerBrowserBtn.BackgroundColor3=THEME.Background; ServerBrowserBtn.Size=UDim2.new(0,265,0,24); ServerBrowserBtn.Position=UDim2.new(0,15,0,205); Instance.new("UICorner", ServerBrowserBtn).CornerRadius=UDim.new(0,4)
local CustomWordsFrame=Instance.new("Frame", ScreenGui); CustomWordsFrame.Name="CustomWordsFrame"; CustomWordsFrame.Size=UDim2.new(0,250,0,350); CustomWordsFrame.Position=UDim2.new(0.5,-125,0.5,-175); CustomWordsFrame.BackgroundColor3=THEME.Background; CustomWordsFrame.Visible=false; CustomWordsFrame.ClipsDescendants=true; EnableDragging(CustomWordsFrame); Instance.new("UICorner", CustomWordsFrame).CornerRadius=UDim.new(0,8); Instance.new("UIStroke", CustomWordsFrame).Color=THEME.Accent
local CWHeader=Instance.new("TextLabel", CustomWordsFrame); CWHeader.Text="Custom Words Manager"; CWHeader.Font=Enum.Font.GothamBold; CWHeader.TextSize=14; CWHeader.TextColor3=THEME.Text; CWHeader.Size=UDim2.new(1,0,0,35); CWHeader.BackgroundTransparency=1
local CWCloseBtn=Instance.new("TextButton", CustomWordsFrame); CWCloseBtn.Text="X"; CWCloseBtn.TextColor3=Color3.fromRGB(255,100,100); CWCloseBtn.Size=UDim2.new(0,30,0,30); CWCloseBtn.Position=UDim2.new(1,-30,0,2); CWCloseBtn.BackgroundTransparency=1; CWCloseBtn.MouseButton1Click:Connect(function() CustomWordsFrame.Visible=false end)
ManageWordsBtn.MouseButton1Click:Connect(function() CustomWordsFrame.Visible=not CustomWordsFrame.Visible; CustomWordsFrame.Parent=nil; CustomWordsFrame.Parent=ScreenGui end)
local function SetupPhantomBox(box, ph) box.Text=ph; box.TextColor3=THEME.SubText; box.Focused:Connect(function() if box.Text==ph then box.Text=""; box.TextColor3=THEME.Text end end) box.FocusLost:Connect(function() if box.Text=="" then box.Text=ph; box.TextColor3=THEME.SubText end end) end
local CWSearchBox=Instance.new("TextBox", CustomWordsFrame); CWSearchBox.Font=Enum.Font.Gotham; CWSearchBox.TextSize=12; CWSearchBox.BackgroundColor3=THEME.ItemBG; CWSearchBox.Size=UDim2.new(1,-20,0,24); CWSearchBox.Position=UDim2.new(0,10,0,35); Instance.new("UICorner", CWSearchBox).CornerRadius=UDim.new(0,4); SetupPhantomBox(CWSearchBox, "Search words...")
local CWScroll=Instance.new("ScrollingFrame", CustomWordsFrame); CWScroll.Size=UDim2.new(1,-10,1,-110); CWScroll.Position=UDim2.new(0,5,0,65); CWScroll.BackgroundTransparency=1; CWScroll.ScrollBarThickness=2; CWScroll.ScrollBarImageColor3=THEME.Accent; local CWListLayout=Instance.new("UIListLayout", CWScroll); CWListLayout.SortOrder=Enum.SortOrder.LayoutOrder; CWListLayout.Padding=UDim.new(0,2)
local CWAddBox=Instance.new("TextBox", CustomWordsFrame); CWAddBox.Font=Enum.Font.Gotham; CWAddBox.TextSize=12; CWAddBox.BackgroundColor3=THEME.ItemBG; CWAddBox.Size=UDim2.new(0,170,0,24); CWAddBox.Position=UDim2.new(0,10,1,-35); Instance.new("UICorner", CWAddBox).CornerRadius=UDim.new(0,4); SetupPhantomBox(CWAddBox, "Add new word...")
local CWAddBtn=Instance.new("TextButton", CustomWordsFrame); CWAddBtn.Text="Add"; CWAddBtn.Font=Enum.Font.GothamBold; CWAddBtn.TextSize=11; CWAddBtn.TextColor3=THEME.Success; CWAddBtn.BackgroundColor3=THEME.ItemBG; CWAddBtn.Size=UDim2.new(0,50,0,24); CWAddBtn.Position=UDim2.new(1,-60,1,-35); Instance.new("UICorner", CWAddBtn).CornerRadius=UDim.new(0,4)
local function RefreshCustomWords()
    for _,c in ipairs(CWScroll:GetChildren()) do if c:IsA("Frame") then c:Destroy() end end
    local q=CWSearchBox.Text; q=(q=="Search words...") and "" or q:lower():gsub("[%s%c]+",""); local list=Config.CustomWords or {}; local sc=0
    for i,w in ipairs(list) do if q=="" or w:find(q,1,true) then sc=sc+1; local r=Instance.new("TextButton", CWScroll); r.Size=UDim2.new(1,-6,0,22); r.BackgroundColor3=(sc%2==0) and Color3.fromRGB(25,25,30) or Color3.fromRGB(30,30,35); r.Text=""; Instance.new("UICorner", r).CornerRadius=UDim.new(0,4); r.MouseButton1Click:Connect(function() SmartType(w,lastDetected,true,true); Tween(r,{BackgroundColor3=THEME.Accent},0.2); task.delay(0.2,function() Tween(r,{BackgroundColor3=(sc%2==0) and Color3.fromRGB(25,25,30) or Color3.fromRGB(30,30,35)},0.2) end) end)
    local l=Instance.new("TextLabel", r); l.Text=w; l.Font=Enum.Font.Gotham; l.TextSize=12; l.TextColor3=THEME.Text; l.Size=UDim2.new(1,-30,1,0); l.Position=UDim2.new(0,5,0,0); l.BackgroundTransparency=1; l.TextXAlignment=Enum.TextXAlignment.Left
    local d=Instance.new("TextButton", r); d.Text="X"; d.Font=Enum.Font.GothamBold; d.TextSize=11; d.TextColor3=Color3.fromRGB(255,80,80); d.Size=UDim2.new(0,22,1,0); d.Position=UDim2.new(1,-22,0,0); d.BackgroundTransparency=1; d.MouseButton1Click:Connect(function() table.remove(Config.CustomWords,i); SaveConfig(); Blacklist[w]=true; RefreshCustomWords(); ShowToast("Removed: "..w,"warning") end) end end CWScroll.CanvasSize=UDim2.new(0,0,0,sc*24)
end
CWSearchBox:GetPropertyChangedSignal("Text"):Connect(RefreshCustomWords); CWAddBtn.MouseButton1Click:Connect(function() local t=CWAddBox.Text; if t=="Add new word..." then return end t=t:gsub("[%s%c]+",""):lower(); if #t<2 then return end if not Config.CustomWords then Config.CustomWords={} end for _,w in ipairs(Config.CustomWords) do if w==t then ShowToast("Word already in custom list!","warning") return end end local e=false; local c=t:sub(1,1); if Buckets and Buckets[c] then for _,w in ipairs(Buckets[c]) do if w==t then e=true break end end end if e then ShowToast("Word already in main dictionary!","error") return end table.insert(Config.CustomWords,t); SaveConfig(); table.insert(Words,t); if c=="" then c="#" end Buckets[c]=Buckets[c] or {}; table.insert(Buckets[c],t); CWAddBox.Text=""; CWAddBox:ReleaseFocus(); RefreshCustomWords(); ShowToast("Added custom word: "..t,"success") end); RefreshCustomWords()
local ServerFrame=Instance.new("Frame", ScreenGui); ServerFrame.Name="ServerBrowser"; ServerFrame.Size=UDim2.new(0,350,0,400); ServerFrame.Position=UDim2.new(0.5,-175,0.5,-200); ServerFrame.BackgroundColor3=THEME.Background; ServerFrame.Visible=false; ServerFrame.ClipsDescendants=true; EnableDragging(ServerFrame); Instance.new("UICorner", ServerFrame).CornerRadius=UDim.new(0,8); Instance.new("UIStroke", ServerFrame).Color=THEME.Accent
local SBHeader=Instance.new("TextLabel", ServerFrame); SBHeader.Text="Server Browser"; SBHeader.Font=Enum.Font.GothamBold; SBHeader.TextSize=16; SBHeader.TextColor3=THEME.Text; SBHeader.Size=UDim2.new(1,0,0,40); SBHeader.BackgroundTransparency=1; local SBClose=Instance.new("TextButton", ServerFrame); SBClose.Text="X"; SBClose.TextColor3=Color3.fromRGB(255,100,100); SBClose.Size=UDim2.new(0,40,0,40); SBClose.Position=UDim2.new(1,-40,0,0); SBClose.BackgroundTransparency=1; SBClose.MouseButton1Click:Connect(function() ServerFrame.Visible=false end)
local SBList=Instance.new("ScrollingFrame", ServerFrame); SBList.Size=UDim2.new(1,-20,1,-90); SBList.Position=UDim2.new(0,10,0,50); SBList.BackgroundTransparency=1; SBList.ScrollBarThickness=3; SBList.ScrollBarImageColor3=THEME.Accent; local SBLayout=Instance.new("UIListLayout", SBList); SBLayout.Padding=UDim.new(0,5); SBLayout.SortOrder=Enum.SortOrder.LayoutOrder
local ServerSortMode="Smallest"; local SBSortBtn=Instance.new("TextButton", ServerFrame); SBSortBtn.Text="Sort: Smallest"; SBSortBtn.Font=Enum.Font.GothamBold; SBSortBtn.TextSize=12; SBSortBtn.BackgroundColor3=THEME.ItemBG; SBSortBtn.TextColor3=THEME.SubText; SBSortBtn.Size=UDim2.new(0.5,-15,0,30); SBSortBtn.Position=UDim2.new(0,10,1,-40); Instance.new("UICorner", SBSortBtn).CornerRadius=UDim.new(0,6)
local SBRefresh=Instance.new("TextButton", ServerFrame); SBRefresh.Text="Refresh"; SBRefresh.Font=Enum.Font.GothamBold; SBRefresh.TextSize=12; SBRefresh.BackgroundColor3=THEME.Accent; SBRefresh.Size=UDim2.new(0.5,-15,0,30); SBRefresh.Position=UDim2.new(0.5,5,1,-40); Instance.new("UICorner", SBRefresh).CornerRadius=UDim.new(0,6)
local function FetchServers()
    SBRefresh.Text="..."; for _,c in ipairs(SBList:GetChildren()) do if c:IsA("Frame") then c:Destroy() end end
    task.spawn(function() local s,r=pcall(function() return request({Url="https://games.roblox.com/v1/games/"..game.PlaceId.."/servers/Public?sortOrder=Asc&limit=100",Method="GET"}) end)
    if s and r and r.Body then local d=HttpService:JSONDecode(r.Body); if d and d.data then local svs=d.data; if ServerSortMode=="Smallest" then table.sort(svs,function(a,b) return (a.playing or 0)<(b.playing or 0) end) else table.sort(svs,function(a,b) return (a.playing or 0)>(b.playing or 0) end) end
    for _,srv in ipairs(svs) do if srv.playing and srv.maxPlayers and srv.id~=game.JobId then local r=Instance.new("Frame", SBList); r.Size=UDim2.new(1,-6,0,45); r.BackgroundColor3=THEME.ItemBG; Instance.new("UICorner", r).CornerRadius=UDim.new(0,6); local i=Instance.new("TextLabel", r); i.Text="Players: "..srv.playing.." / "..srv.maxPlayers.."\nPing: "..(srv.ping or "?").."ms"; i.Size=UDim2.new(0.6,0,1,0); i.Position=UDim2.new(0,10,0,0); i.BackgroundTransparency=1; i.TextColor3=THEME.Text; i.Font=Enum.Font.Gotham; i.TextSize=12; i.TextXAlignment=Enum.TextXAlignment.Left
    local j=Instance.new("TextButton", r); j.Text="Join"; j.BackgroundColor3=Color3.fromRGB(100,200,100); j.Size=UDim2.new(0,80,0,25); j.Position=UDim2.new(1,-90,0.5,-12.5); j.Font=Enum.Font.GothamBold; j.TextColor3=Color3.new(1,1,1); Instance.new("UICorner", j).CornerRadius=UDim.new(0,4); j.MouseButton1Click:Connect(function() j.Text="Joining..."; ShowToast("Teleporting...","success"); if queue_on_teleport then queue_on_teleport('loadstring(game:HttpGet("https://raw.githubusercontent.com/skrylor/Last-Letter-Script/refs/heads/main/Last%20Letter.lua"))()') end task.spawn(function() local s,e=pcall(function() game:GetService("TeleportService"):TeleportToPlaceInstance(game.PlaceId, srv.id, Players.LocalPlayer) end) if not s then j.Text="Failed"; ShowToast("Teleport Failed: "..tostring(e),"error"); task.wait(2); j.Text="Join" end end) end) end end SBList.CanvasSize=UDim2.new(0,0,0,SBLayout.AbsoluteContentSize.Y) end else ShowToast("Failed to fetch servers","error") end SBRefresh.Text="Refresh" end)
end
SBSortBtn.MouseButton1Click:Connect(function() ServerSortMode=(ServerSortMode=="Smallest") and "Largest" or "Smallest"; SBSortBtn.Text="Sort: "..ServerSortMode; FetchServers() end); SBRefresh.MouseButton1Click:Connect(FetchServers); ServerBrowserBtn.MouseButton1Click:Connect(function() ServerFrame.Visible=not ServerFrame.Visible; ServerFrame.Parent=nil; ServerFrame.Parent=ScreenGui; if ServerFrame.Visible then FetchServers() end end)
do
    local WordBrowserFrame=Instance.new("Frame", ScreenGui); WordBrowserFrame.Name="WordBrowser"; WordBrowserFrame.Size=UDim2.new(0,300,0,400); WordBrowserFrame.Position=UDim2.new(0.5,-150,0.5,-200); WordBrowserFrame.BackgroundColor3=THEME.Background; WordBrowserFrame.Visible=false; WordBrowserFrame.ClipsDescendants=true; EnableDragging(WordBrowserFrame); Instance.new("UICorner", WordBrowserFrame).CornerRadius=UDim.new(0,8); Instance.new("UIStroke", WordBrowserFrame).Color=THEME.Accent
    local WBClose=Instance.new("TextButton", WordBrowserFrame); WBClose.Text="X"; WBClose.TextColor3=Color3.fromRGB(255,100,100); WBClose.Size=UDim2.new(0,40,0,40); WBClose.Position=UDim2.new(1,-40,0,0); WBClose.BackgroundTransparency=1; WBClose.MouseButton1Click:Connect(function() WordBrowserFrame.Visible=false end)
    local WBStartBox=Instance.new("TextBox", WordBrowserFrame); WBStartBox.BackgroundColor3=THEME.ItemBG; WBStartBox.Size=UDim2.new(0.4,0,0,24); WBStartBox.Position=UDim2.new(0,10,0,45); Instance.new("UICorner", WBStartBox).CornerRadius=UDim.new(0,4); SetupPhantomBox(WBStartBox, "Starts with...")
    local WBEndBox=Instance.new("TextBox", WordBrowserFrame); WBEndBox.BackgroundColor3=THEME.ItemBG; WBEndBox.Size=UDim2.new(0.4,0,0,24); WBEndBox.Position=UDim2.new(0.45,0,0,45); Instance.new("UICorner", WBEndBox).CornerRadius=UDim.new(0,4); SetupPhantomBox(WBEndBox, "Ends with...")
    local WBLengthBox=Instance.new("TextBox", WordBrowserFrame); WBLengthBox.BackgroundColor3=THEME.ItemBG; WBLengthBox.Size=UDim2.new(0.2,0,0,24); WBLengthBox.Position=UDim2.new(0.02,0,0,80); Instance.new("UICorner", WBLengthBox).CornerRadius=UDim.new(0,4); SetupPhantomBox(WBLengthBox, "Len...")
    local WBSearchBtn=Instance.new("TextButton", WordBrowserFrame); WBSearchBtn.Text="Go"; WBSearchBtn.BackgroundColor3=THEME.Accent; WBSearchBtn.Size=UDim2.new(0.1,0,0,24); WBSearchBtn.Position=UDim2.new(0.88,0,0,45); Instance.new("UICorner", WBSearchBtn).CornerRadius=UDim.new(0,4)
    local WBList=Instance.new("ScrollingFrame", WordBrowserFrame); WBList.Size=UDim2.new(1,-20,1,-125); WBList.Position=UDim2.new(0,10,0,115); WBList.BackgroundTransparency=1; WBList.ScrollBarThickness=3; WBList.ScrollBarImageColor3=THEME.Accent; local WBLayout=Instance.new("UIListLayout", WBList); WBLayout.Padding=UDim.new(0,2); WBLayout.SortOrder=Enum.SortOrder.LayoutOrder
    local function SearchWords()
        for _,c in ipairs(WBList:GetChildren()) do if c:IsA("GuiObject") and c.Name~="UIListLayout" then c:Destroy() end end
        local s,e,l = WBStartBox.Text, WBEndBox.Text, tonumber(WBLengthBox.Text); if s=="Starts with..." then s="" end if e=="Ends with..." then e="" end s=s:lower():gsub("[%s%c]+",""); e=e:lower():gsub("[%s%c]+",""); suffixMode=e; Config.SuffixMode=e; lengthMode=l or 0; Config.LengthMode=lengthMode; if UpdateList then UpdateList(lastDetected, lastRequiredLetter) end if s=="" and e=="" and not l then return end
        local res={}; local bucket=Words; if s~="" then local c=s:sub(1,1); if Buckets and Buckets[c] then bucket=Buckets[c] end end
        for _,w in ipairs(bucket) do if (s=="" or w:sub(1,#s)==s) and (e=="" or w:sub(-#e)==e) and ((not l) or #w==l) then table.insert(res,w) if #res>=200 then break end end end
        for i,w in ipairs(res) do local r=Instance.new("TextButton", WBList); r.Size=UDim2.new(1,-6,0,22); r.BackgroundColor3=(i%2==0) and Color3.fromRGB(25,25,30) or Color3.fromRGB(30,30,35); r.Text=""; Instance.new("UICorner", r).CornerRadius=UDim.new(0,4); r.MouseButton1Click:Connect(function() SmartType(w,lastDetected,true,true); Tween(r,{BackgroundColor3=THEME.Accent},0.2); task.delay(0.2,function() Tween(r,{BackgroundColor3=(i%2==0) and Color3.fromRGB(25,25,30) or Color3.fromRGB(30,30,35)},0.2) end) end); local l=Instance.new("TextLabel", r); l.Text=w; l.Font=Enum.Font.Gotham; l.TextColor3=THEME.Text; l.Size=UDim2.new(1,-10,1,0); l.Position=UDim2.new(0,5,0,0); l.BackgroundTransparency=1; l.TextXAlignment=Enum.TextXAlignment.Left end WBList.CanvasSize=UDim2.new(0,0,0,WBLayout.AbsoluteContentSize.Y)
    end
    WBSearchBtn.MouseButton1Click:Connect(SearchWords); WBStartBox.FocusLost:Connect(function(e) if e then SearchWords() end end); WBEndBox.FocusLost:Connect(function(e) if e then SearchWords() end end); WBLengthBox.FocusLost:Connect(function(e) if e then SearchWords() end end)
    WordBrowserBtn.MouseButton1Click:Connect(function() WordBrowserFrame.Visible=not WordBrowserFrame.Visible; WordBrowserFrame.Parent=nil; WordBrowserFrame.Parent=ScreenGui end)
end
local function CalculateDelay() local base=60/currentCPM; local var=base*0.4; return useHumanization and (base+math.random()*var-(var/2)) or base end
local KEY_POS = {}; local r1,r2,r3="qwertyuiop","asdfghjkl","zxcvbnm"; for i=1,#r1 do KEY_POS[r1:sub(i,i)]={x=i,y=1} end for i=1,#r2 do KEY_POS[r2:sub(i,i)]={x=i+0.5,y=2} end for i=1,#r3 do KEY_POS[r3:sub(i,i)]={x=i+1,y=3} end
local function KeyDistance(a,b) if not a or not b then return 1 end local pa,pb=KEY_POS[a:lower()],KEY_POS[b:lower()]; if not pa or not pb then return 1 end return math.sqrt((pa.x-pb.x)^2 + (pa.y-pb.y)^2) end
local lastKey = nil; local function CalculateDelayForKeys(p,n) if isBlatant then return 60/currentCPM end local base=60/currentCPM; local var=base*0.35; local ex=0; if useHumanization and useFingerModel and p and n and p~="" then local d=KeyDistance(p,n); ex=d*0.018*(550/math.max(150,currentCPM)); local pa,pb=KEY_POS[p:lower()],KEY_POS[n:lower()]; if pa and pb and ((pa.x<=5 and pb.x<=5) or (pa.x>5 and pb.x>5)) then ex=ex*0.8 end end if useHumanization then local r=(math.random()+math.random()+math.random())/3; local n=(r*2-1)*var; return math.max(0.005, base+ex+n) else return base end end
local VirtualUser = game:GetService("VirtualUser"); local function GetKeyCode(c) local l=Config.KeyboardLayout or "QWERTY"; if type(c)=="string" and #c==1 then c=c:lower(); if l=="QWERTZ" then if c=="z" then return Enum.KeyCode.Y elseif c=="y" then return Enum.KeyCode.Z end elseif l=="AZERTY" then if c=="a" then return Enum.KeyCode.Q elseif c=="q" then return Enum.KeyCode.A elseif c=="z" then return Enum.KeyCode.W elseif c=="w" then return Enum.KeyCode.Z elseif c=="m" then return Enum.KeyCode.Semicolon end end return Enum.KeyCode[c:upper()] end return nil end
local function SimulateKey(inp)
    if typeof(inp)=="string" and #inp==1 then local s=pcall(function() VirtualInputManager:SendTextInput(inp) end); if not s then local k; pcall(function() k=GetKeyCode(inp) end); if not k then pcall(function() k=Enum.KeyCode[inp:upper()] end) end if k then pcall(function() VirtualInputManager:SendKeyEvent(true,k,false,game); task.wait(0.01); VirtualInputManager:SendKeyEvent(false,k,false,game) end) end end return end
    local k; if typeof(inp)=="EnumItem" then k=inp else pcall(function() k=Enum.KeyCode[inp:upper()] end) end
    if k then local bh=math.clamp(12/currentCPM,0.015,0.05); local h=isBlatant and 0.002 or (bh+(math.random()*0.01)-0.005); local s=pcall(function() VirtualInputManager:SendKeyEvent(true,k,false,game); task.wait(h); VirtualInputManager:SendKeyEvent(false,k,false,game) end); if not s then pcall(function() VirtualUser:TypeKey(k) end) end end
end
local function Backspace(cnt) local f=UserInputService:GetFocusedTextBox(); if f and f:IsDescendantOf(game) and f.TextEditable then f.Text=f.Text:sub(1,-cnt-1); lastKey=nil return end local k=Enum.KeyCode.Backspace; for i=1,cnt do pcall(function() VirtualInputManager:SendKeyEvent(true,k,false,game); VirtualInputManager:SendKeyEvent(false,k,false,game) end); if i%20==0 then task.wait() end end lastKey=nil end
local function PressEnter() SimulateKey(Enum.KeyCode.Return); lastKey=nil end
local function GetGameTextBox() local p=Players.LocalPlayer; local g=p and p:FindFirstChild("PlayerGui"); local ig=g and g:FindFirstChild("InGame"); if ig then local f=ig:FindFirstChild("Frame"); if f then for _,c in ipairs(f:GetDescendants()) do if c:IsA("TextBox") and c.Visible then return c end end end for _,c in ipairs(ig:GetDescendants()) do if c:IsA("TextBox") and c.Visible then return c end end end return UserInputService:GetFocusedTextBox() end
local function SmartType(target, current, isCorrection, bypass)
    if unloaded then return end if isTyping then if (tick()-lastTypingStart)>15 then isTyping=false; isAutoPlayScheduled=false; StatusText.Text="Typing Reset"; StatusText.TextColor3=THEME.Warning else return end end
    isTyping=true; lastTypingStart=tick(); local tb=GetGameTextBox(); if tb then tb:CaptureFocus(); task.wait(0.1) end StatusText.Text="Typing..."; StatusText.TextColor3=THEME.Accent; Tween(StatusDot,{BackgroundColor3=THEME.Accent})
    local s,e=pcall(function()
        if isCorrection then
            local com=0; local min=math.min(#target,#current); for i=1,min do if target:sub(i,i)==current:sub(i,i) then com=i else break end end
            local bs=#current-com; if bs>0 then Backspace(bs); task.wait(0.15) end
            local tt=target:sub(com+1); for i=1,#tt do if not bypass and not GetTurnInfo() then task.wait(0.05); if not GetTurnInfo() then break end end local c=tt:sub(i,i); SimulateKey(c); task.wait(CalculateDelayForKeys(lastKey,c)); lastKey=c; if useHumanization and math.random()<0.03 then task.wait(0.15+math.random()*0.45) end end
            if not riskyMistakes then task.wait(0.1); local fc=GetGameTextBox(); if fc and fc.Text~=target then StatusText.Text="Mismatch!"; StatusText.TextColor3=THEME.Warning; Backspace(#fc.Text); isTyping=false; forceUpdateList=true return end end
            PressEnter(); local vs=tick(); local acc=false; while (tick()-vs)<1.5 do local cc=GetCurrentGameWord(); if cc=="" or (cc~=target and cc~=current) then acc=true break end task.wait(0.05) end
            if not acc then Blacklist[target]=true; RandomPriority[target]=nil; for k,l in pairs(RandomOrderCache) do for i=#l,1,-1 do if l[i]==target then table.remove(l,i) end end end StatusText.Text="Rejected: "..target; StatusText.TextColor3=THEME.Warning; local f=UserInputService:GetFocusedTextBox(); if f and f:IsDescendantOf(game) and f.TextEditable then f.Text="" else Backspace(#target+5) end lastDetected="---"; isTyping=false; forceUpdateList=true return else StatusText.Text="Cleared"; StatusText.TextColor3=THEME.SubText; local cur=GetCurrentGameWord(); if #cur>0 then Backspace(#cur) end UsedWords[target]=true; isMyTurnLogDetected=false; task.wait(0.2) end
        else
            local mp=""; if target:sub(1,#current)==current then mp=target:sub(#current+1) else mp=target end local ab="abcdefghijklmnopqrstuvwxyz"
            for i=1,#mp do if not bypass and not GetTurnInfo() then task.wait(0.05); if not GetTurnInfo() then break end end local c=mp:sub(i,i)
                if errorRate>0 and (math.random()<(errorRate/100)) then local tc; repeat local idx=math.random(1,#ab); tc=ab:sub(idx,idx) until tc~=c; SimulateKey(tc); if riskyMistakes then task.wait(0.05+math.random()*0.1); PressEnter() end task.wait(CalculateDelayForKeys(lastKey,tc)); lastKey=tc; task.wait(thinkDelayCurrent*(0.6+math.random()*0.8)); SimulateKey(Enum.KeyCode.Backspace); lastKey=nil; task.wait(0.05+math.random()*0.08); SimulateKey(c); task.wait(CalculateDelayForKeys(lastKey,c)); lastKey=c else SimulateKey(c); task.wait(CalculateDelayForKeys(lastKey,c)); lastKey=c end if useHumanization and math.random()<0.03 then task.wait(0.12+math.random()*0.5) end
            end
            if not riskyMistakes then task.wait(0.1); local fc=GetGameTextBox(); if fc and fc.Text~=target then StatusText.Text="Mismatch!"; StatusText.TextColor3=THEME.Warning; Backspace(#fc.Text); isTyping=false; forceUpdateList=true return end end
            PressEnter(); local vs=tick(); local acc=false; while (tick()-vs)<1.5 do local cc=GetCurrentGameWord(); if cc=="" or (cc~=target and cc~=current) then acc=true break end task.wait(0.05) end
            if not acc then local pc=GetGameTextBox(); if pc and pc.Text==target then StatusText.Text="Retrying..."; PressEnter(); task.wait(0.5); if GetCurrentGameWord()==current then StatusText.Text="Failed (Lag?)"; StatusText.TextColor3=THEME.Warning; Backspace(#target); isTyping=false; forceUpdateList=true return end end Blacklist[target]=true; for k,l in pairs(RandomOrderCache) do for i=#l,1,-1 do if l[i]==target then table.remove(l,i) end end end StatusText.Text="Rejected: "..target; StatusText.TextColor3=THEME.Warning; local f=UserInputService:GetFocusedTextBox(); if f and f:IsDescendantOf(game) and f.TextEditable then f.Text="" else Backspace(#target+5) end isTyping=false; lastDetected="---"; forceUpdateList=true; task.spawn(function() task.wait(0.1); local _,r=GetTurnInfo(); UpdateList(current,r) end) return else StatusText.Text="Verified"; StatusText.TextColor3=THEME.Warning; local cur=GetCurrentGameWord(); if #cur>0 then Backspace(#cur) end UsedWords[target]=true; isMyTurnLogDetected=false; task.wait(0.2) end
        end
    end); isTyping=false; forceUpdateList=true
end
local function GetMatchLength(s,p) local l=0; for i=1,math.min(#s,#p) do if p:byte(i)==35 or p:byte(i)==s:byte(i) then l=i else break end end return l end
local function BinarySearchStart(l,p) local lt,rt,res,pl=1,#l,-1,#p; while lt<=rt do local m=math.floor((lt+rt)/2); local w=l[m]; local s=w:sub(1,pl); if s==p then res=m; rt=m-1 elseif s<p then lt=m+1 else rt=m-1 end end return res end
UpdateList = function(detected, req)
    local matches, sp, backtracked, manual = {}, detected, false, false
    if SearchBox and SearchBox.Text~="" then sp=SearchBox.Text:lower():gsub("[%s%c]+",""); manual=true; if req and sp:sub(1,1)~=req:sub(1,1):lower() then req=nil end end
    if not manual and req and #req>0 then local rl=GetMatchLength(req,sp); if rl==#sp and #req>#sp then sp=req end end
    local fc=sp:sub(1,1); if fc=="#" then fc=nil end; if (not fc or fc=="") and req then fc=req:sub(1,1):lower() end
    local bucket=(fc and fc~="" and Buckets) and Buckets[fc] or Words
    local function Collect(pfx, fallback)
        local ex,part,mpl,lim={},{},0,100; if bucket then
            local check=function(w) if Blacklist[w] or UsedWords[w] then return end if suffixMode~="" and w:sub(-#suffixMode)~=suffixMode then return end local lm=true; if not fallback and lengthMode>0 then lm=(#w==lengthMode) elseif fallback and lengthMode>0 then lm=true end if not lm then return end local ml=GetMatchLength(w,pfx); if ml==#pfx then table.insert(ex,w) elseif #ex==0 then if ml>mpl then mpl=ml; part={w} elseif ml==mpl and ml>0 and #part<50 then table.insert(part,w) end end end
            local ub=true; if pfx:find("#") or pfx:find("%*") then ub=false end
            if ub and #pfx>0 then local si=BinarySearchStart(bucket,pfx); if si~=-1 then local cnt=0; for i=si,#bucket do local w=bucket[i]; if w:sub(1,#pfx)~=pfx then break end check(w); cnt=cnt+1; if cnt>=3000 then break end end end else local slim=(sortMode=="Random") and 1000 or lim; for _,w in ipairs(bucket) do check(w); if #ex>=slim then break end end end if sortMode=="Random" and #ex>0 then shuffleTable(ex) end
        end return ex,part,mpl
    end
    local ex,part,pl=Collect(sp,false); if #ex==0 and lengthMode>0 then local fex=Collect(sp,true); if #fex>0 then ex=fex end end
    if #ex>0 then matches=ex elseif pl>0 then matches=part; sp=sp:sub(1,pl); backtracked=true elseif req and #req>0 then local rc=req:sub(1,1):lower(); if sp:sub(1,1):lower()~=rc then local fb=(Buckets and Buckets[rc]) or Words; if fb then for _,w in ipairs(fb) do if not Blacklist[w] and not UsedWords[w] then local ml=GetMatchLength(w,req); if ml==#req then table.insert(matches,w); if #matches>=100 then break end end end end end end if #matches>0 then sp=req; backtracked=true end end
    end
    if #matches>0 then if sortMode=="Longest" then table.sort(matches,function(a,b) return #a>#b end) elseif sortMode=="Shortest" then table.sort(matches,function(a,b) return #a<#b end) elseif sortMode=="Killer" then table.sort(matches,function(a,b) local sa,sb=GetKillerScore(a),GetKillerScore(b); if sa==sb then return #a<#b end return sa>sb end) end end
    local disp={}; for i=1,math.min(40,#matches) do table.insert(disp,matches[i]) end
    if showKeyboard and KeyboardFrame.Visible then local cols={Color3.fromRGB(100,255,140),Color3.fromRGB(255,180,200),Color3.fromRGB(100,200,255)}; local tks={}; for i=1,math.min(3,#disp) do local nc=disp[i]:sub(#sp+1,#sp+1); if nc and nc~="" then local c=nc:lower(); if not tks[c] then tks[c]=i end end end for c,k in pairs(Keys) do if tks[c] then k.BackgroundColor3=Color3.new(1,1,1); Tween(k,{BackgroundColor3=cols[tks[c]]},0.3) else Tween(k,{BackgroundColor3=THEME.ItemBG},0.2) end end end
    if #matches>0 and not backtracked then currentBestMatch=matches[1] else currentBestMatch=nil end
    if backtracked then local v=sp; local i=detected:sub(#sp+1); local ac=ColorToRGB(THEME.Accent); StatusText.Text="No match: <font color=\"rgb("..ac..")\">"..v.."</font><font color=\"rgb(255,80,80)\">"..i.."</font>"; StatusText.TextColor3=THEME.SubText elseif #ex==0 and lengthMode>0 and suffixMode~="" then StatusText.Text="No len match"; StatusText.TextColor3=THEME.Warning end
    for i=1,math.max(#disp,#ButtonCache) do local w,b=disp[i],ButtonCache[i]; if w then local l; if not b then b=Instance.new("TextButton"); b.Size=UDim2.new(1,-6,0,30); b.BackgroundColor3=THEME.ItemBG; b.Text=""; b.AutoButtonColor=false; Instance.new("UICorner",b).CornerRadius=UDim.new(0,6); l=Instance.new("TextLabel",b); l.Name="Label"; l.Size=UDim2.new(1,-20,1,0); l.Position=UDim2.new(0,10,0,0); l.BackgroundTransparency=1; l.Font=Enum.Font.GothamMedium; l.TextSize=14; l.TextXAlignment=Enum.TextXAlignment.Left; l.RichText=true; b.MouseEnter:Connect(function() Tween(b,{BackgroundColor3=Color3.fromRGB(45,45,55)}) end); b.MouseLeave:Connect(function() Tween(b,{BackgroundColor3=THEME.ItemBG}) end); b.MouseButton1Click:Connect(function() local d=ButtonData[b]; if d then SmartType(d.word,d.detected,true); local ll=b:FindFirstChild("Label"); if ll then ll.TextColor3=THEME.Success end Tween(b,{BackgroundColor3=Color3.fromRGB(30,60,40)}) end end); b.Parent=ScrollList; table.insert(ButtonCache,b) else l=b:FindFirstChild("Label"); b.Visible=true; b.Parent=ScrollList; b.BackgroundColor3=THEME.ItemBG; if l then l.TextColor3=THEME.Text end end ButtonData[b]={word=w,detected=detected}; local ac,tc=ColorToRGB(THEME.Accent),ColorToRGB(THEME.Text); if i==1 then ac="100,255,140" elseif i==2 then ac="255,180,200" elseif i==3 then ac="100,200,255" end local pf,sf; if backtracked then pf=w:sub(1,#sp); sf=w:sub(#sp+1) else pf=w:sub(1,#detected); sf=w:sub(#detected+1) end if l then l.Text="<font color=\"rgb("..ac..")\">"..pf.."</font><font color=\"rgb("..tc..")\">"..sf.."</font>" end else if b then b.Visible=false; ButtonData[b]=nil end end end ScrollList.CanvasSize=UDim2.new(0,0,0,UIListLayout.AbsoluteContentSize.Y)
end
SetupSlider(SliderBtn, SliderBg, SliderFill, function(p) local max=isBlatant and MAX_CPM_BLATANT or MAX_CPM_LEGIT; currentCPM=math.floor(MIN_CPM+(p*(max-MIN_CPM))); SliderFill.Size=UDim2.new(p,0,1,0); SliderLabel.Text="Speed: "..currentCPM.." CPM"; if currentCPM>900 then Tween(SliderFill,{BackgroundColor3=Color3.fromRGB(255,80,80)}) else Tween(SliderFill,{BackgroundColor3=THEME.Accent}) end end)
MinBtn.MouseButton1Click:Connect(function() local m=MainFrame.Size.Y.Offset<100; if not m then Tween(MainFrame,{Size=UDim2.new(0,300,0,45)}); ScrollList.Visible=false; SettingsFrame.Visible=false; StatusFrame.Visible=false; MinBtn.Text="+" else Tween(MainFrame,{Size=UDim2.new(0,300,0,500)}); task.wait(0.2); ScrollList.Visible=true; SettingsFrame.Visible=true; StatusFrame.Visible=true; MinBtn.Text="-" end end)
local lastTypeVisible, lastRequiredLetter = false, ""; local StatsData={}
do local sf=Instance.new("Frame",ScreenGui); sf.Name="StatsFrame"; sf.Size=UDim2.new(0,120,0,60); sf.Position=UDim2.new(0.5,-60,0,10); sf.BackgroundColor3=THEME.Background; sf.Visible=false; EnableDragging(sf); Instance.new("UICorner",sf).CornerRadius=UDim.new(0,8); Instance.new("UIStroke",sf).Color=THEME.Accent; StatsData.Frame=sf; local st=Instance.new("TextLabel",sf); st.Size=UDim2.new(1,0,0,25); st.Position=UDim2.new(0,0,0,5); st.BackgroundTransparency=1; st.TextColor3=THEME.Text; st.Font=Enum.Font.GothamBold; st.TextSize=20; st.Text="--"; StatsData.Timer=st; local sc=Instance.new("TextLabel",sf); sc.Size=UDim2.new(1,0,0,20); sc.Position=UDim2.new(0,0,0,30); sc.BackgroundTransparency=1; sc.TextColor3=THEME.SubText; sc.Font=Enum.Font.Gotham; sc.TextSize=12; sc.Text="Words: 0"; StatsData.Count=sc end
runConn = RunService.RenderStepped:Connect(function()
    pcall(function()
        local now=tick(); local p=Players.LocalPlayer; local g=p and p:FindFirstChild("PlayerGui"); local f=g and g:FindFirstChild("InGame") and g.InGame:FindFirstChild("Frame"); if isTyping and (tick()-lastTypingStart)>15 then isTyping=false; isAutoPlayScheduled=false; StatusText.Text="Watchdog Reset"; StatusText.TextColor3=THEME.Warning end
        local v=false; if f and f.Parent then if f.Parent:IsA("ScreenGui") then v=f.Parent.Enabled elseif f.Parent:IsA("GuiObject") then v=f.Parent.Visible end end
        local sec; if v then local c=f:FindFirstChild("Circle"); local tl=c and c:FindFirstChild("Timer") and c.Timer:FindFirstChild("Seconds"); if tl then sec=tonumber(tl.Text:match("([%d%.]+)")); StatsData.Frame.Visible=true; StatsData.Timer.Text=tl.Text; StatsData.Timer.TextColor3=(sec and sec<3) and Color3.fromRGB(255,80,80) or THEME.Text end else StatsData.Frame.Visible=false end
        local imt,rl=GetTurnInfo(f); if (now-lastWordCheck)>0.05 then cachedDetected,cachedCensored=GetCurrentGameWord(f); lastWordCheck=now end local det,cen=cachedDetected,cachedCensored
        if v and imt and not isTyping and sec and sec<1.5 then local c=(rl or ""):lower(); local b=Buckets[c]; if b then local bw,bl=nil,999; for _,w in ipairs(b) do if not Blacklist[w] and not UsedWords[w] and w:sub(1,#det)==det then if #w<bl then bw=w; bl=#w end end end if bw then StatusText.Text="PANIC SAVE!"; StatusText.TextColor3=Color3.fromRGB(255,50,50); SmartType(bw,det,false) end end end
        if autoJoin and (now-lastAutoJoinCheck>AUTO_JOIN_RATE) then lastAutoJoinCheck=now; task.spawn(function()
            local dm=g and g:FindFirstChild("DisplayMatch"); local df=dm and dm:FindFirstChild("Frame"); local ms=df and df:FindFirstChild("Matches"); if ms then for _,mf in ipairs(ms:GetChildren()) do if (mf:IsA("Frame") or mf:IsA("GuiObject")) and mf.Name~="UIListLayout" then local jb=mf:FindFirstChild("Join"); local tl=mf:FindFirstChild("Title"); local ill=false; local tt="N/A"; if tl and tl:IsA("TextLabel") then tt=tl.Text; if tt:find("Last Letter") then ill=true end end local idx=tonumber(mf.Name); local al=true; if idx then if idx>=1 and idx<=4 then al=Config.AutoJoinSettings._1v1 elseif idx>=5 and idx<=8 then al=Config.AutoJoinSettings._4p elseif idx==9 then al=Config.AutoJoinSettings._8p end end if jb and jb.Visible and ill and al then local mid=mf.Name; if (tick()-(JoinDebounce[mid] or 0))>2 then JoinDebounce[mid]=tick(); task.wait(0.5); local clk=false; if getconnections and jb:IsA("GuiButton") then local s,cn=pcall(function() return getconnections(jb.MouseButton1Click) end) if s and cn then for _,c in ipairs(cn) do if c.Fire then c:Fire() end if c.Function then task.spawn(c.Function) end clk=true end end end end if not clk then local cd=jb:FindFirstChildWhichIsA("ClickDetector"); if cd then fireclickdetector(cd); clk=true end end if not clk then local ap=jb.AbsolutePosition; local as=jb.AbsoluteSize; VirtualInputManager:SendMouseButtonEvent(ap.X+as.X/2, ap.Y+as.Y/2, 0, true, game, 1); task.wait(0.05); VirtualInputManager:SendMouseButtonEvent(ap.X+as.X/2, ap.Y+as.Y/2, 0, false, game, 1) end break end end end end end end) end
        local typeLbl=f and f:FindFirstChild("Type"); local tv=typeLbl and typeLbl.Visible; if tv and not lastTypeVisible then UsedWords={}; StatusText.Text="New Round"; StatusText.TextColor3=THEME.Success end lastTypeVisible=tv
        if cen then if StatusText.Text~="Word is Censored" then StatusText.Text="Word is Censored"; StatusText.TextColor3=THEME.Warning; Tween(StatusDot,{BackgroundColor3=THEME.Warning}); for _,b in ipairs(ButtonCache) do b.Visible=false end StatsData.Count.Text="Words: 0" end listUpdatePending=false; forceUpdateList=false; currentBestMatch=nil; lastDetected=det; lastRequiredLetter=rl end
        if listUpdatePending and (now-lastInputTime>LIST_DEBOUNCE) then listUpdatePending=false; UpdateList(lastDetected, lastRequiredLetter); local vc=0; for _,b in ipairs(ButtonCache) do if b.Visible then vc=vc+1 end end StatsData.Count.Text="Words: "..vc.."+" end
        if not v then if StatusText.Text~="Not in Round" then StatusText.Text="Not in Round"; StatusText.TextColor3=THEME.SubText; Tween(StatusDot,{BackgroundColor3=THEME.SubText}); for _,b in ipairs(ButtonCache) do b.Visible=false end StatsData.Count.Text="Words: 0" end lastDetected="---" elseif det~=lastDetected or rl~=lastRequiredLetter or forceUpdateList then currentBestMatch=nil; lastDetected=det; lastRequiredLetter=rl; if det=="" and not forceUpdateList then StatusText.Text="Waiting..."; StatusText.TextColor3=THEME.SubText; Tween(StatusDot,{BackgroundColor3=THEME.SubText}); UpdateList("",rl); listUpdatePending=false; local vc=0; for _,b in ipairs(ButtonCache) do if b.Visible then vc=vc+1 end end StatsData.Count.Text="Words: "..vc.."+" else if det~="" then local cmp=false; if #det>2 then local c=det:sub(1,1); if c~="#" and Buckets and Buckets[c] then for _,w in ipairs(Buckets[c]) do if w==det then cmp=true break end end end end if cmp then StatusText.Text="Completed: "..det.." ✓"; StatusText.TextColor3=THEME.Success; Tween(StatusDot,{BackgroundColor3=THEME.Success}) else StatusText.Text="Input: "..det; StatusText.TextColor3=THEME.Accent; Tween(StatusDot,{BackgroundColor3=THEME.Warning}) end end if forceUpdateList then listUpdatePending=true; lastInputTime=0; forceUpdateList=false else listUpdatePending=true; lastInputTime=now end end end
        if autoPlay and not isTyping and not isAutoPlayScheduled and currentBestMatch and det==lastDetected then local imtc,_=GetTurnInfo(f); if imtc then isAutoPlayScheduled=true; local tw,snap=currentBestMatch,lastDetected; task.spawn(function() local d=isBlatant and 0.15 or (0.8+math.random()*0.5); task.wait(d); local still,_=GetTurnInfo(); if autoPlay and not isTyping and GetCurrentGameWord()==snap and still then SmartType(tw,snap,false) end isAutoPlayScheduled=false end) end end
    end)
end)
inputConn = UserInputService.InputBegan:Connect(function(i) if unloaded then return end if i.KeyCode==TOGGLE_KEY then ScreenGui.Enabled=not ScreenGui.Enabled end end)
